// Code generated by "ent -type=Example"; DO NOT EDIT

package example

import (
	"fmt"
	"github.com/speedland/go/ent"
	helper "github.com/speedland/go/gae/datastore"
	"github.com/speedland/go/gae/memcache"
	"github.com/speedland/go/keyvalue"
	"github.com/speedland/go/lazy"
	"github.com/speedland/go/x/xlog"
	"github.com/speedland/go/x/xtime"
	"golang.org/x/net/context"
	"google.golang.org/appengine/datastore"
)

func (e *Example) NewKey(ctx context.Context) *datastore.Key {
	return helper.NewKey(ctx, "Example", e.ID)
}

// UpdateByForm updates the fields by form values. All values should be validated
// before calling this function.
func (e *Example) UpdateByForm(form *keyvalue.GetProxy) {
	if v, err := form.Get("digit"); err == nil {
		e.Digit = ent.ParseInt(v.(string))
	}
	if v, err := form.Get("desc"); err == nil {
		e.Desc = v.(string)
	}
	if v, err := form.Get("content_bytes"); err == nil {
		e.ContentBytes = []byte(v.(string))
	}
	if v, err := form.Get("slice_type"); err == nil {
		e.SliceType = ent.ParseStringList(v.(string))
	}
	if v, err := form.Get("bool_type"); err == nil {
		e.BoolType = ent.ParseBool(v.(string))
	}
	if v, err := form.Get("float_type"); err == nil {
		e.FloatType = ent.ParseFloat64(v.(string))
	}
}

// NewExample returns a new *Example with default field values.
func NewExample() *Example {
	e := &Example{}
	e.Digit = 10
	e.Desc = "This is default value"
	e.CreatedAt = ent.ParseTime("$now")
	e.DefaultTime = ent.ParseTime("2016-01-01T20:12:10Z")
	return e
}

type ExampleKind struct {
	BeforeSave        func(ent *Example) error
	AfterSave         func(ent *Example) error
	useDefaultIfNil   bool
	noCache           bool
	noTimestampUpdate bool
}

// DefaultExampleKind is a default value of *ExampleKind
var DefaultExampleKind = &ExampleKind{}

const ExampleKindLoggerKey = "ent.example"

func (k *ExampleKind) UseDefaultIfNil(b bool) *ExampleKind {
	k.useDefaultIfNil = b
	return k
}

// Get gets the kind entity from datastore
func (k *ExampleKind) Get(ctx context.Context, key interface{}) (*datastore.Key, *Example, error) {
	keys, ents, err := k.GetMulti(ctx, key)
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

// MustGet is like Get but returns only values and panic if error happens.
func (k *ExampleKind) MustGet(ctx context.Context, key interface{}) *Example {
	_, v, err := k.Get(ctx, key)
	if err != nil {
		panic(err)
	}
	return v
}

// GetMulti do Get with multiple keys
func (k *ExampleKind) GetMulti(ctx context.Context, keys ...interface{}) ([]*datastore.Key, []*Example, error) {
	var size = len(keys)
	var memKeys []string
	var dsKeys []*datastore.Key
	var ents []*Example
	if size == 0 {
		return nil, nil, nil
	}
	logger := xlog.WithContext(ctx).WithKey(ExampleKindLoggerKey)
	dsKeys = make([]*datastore.Key, size, size)
	for i := range keys {
		dsKeys[i] = helper.NewKey(ctx, "Example", keys[i])
	}
	ents = make([]*Example, size, size)
	// Memcache access
	if !k.noCache {
		logger.Debugf("Trying to get entities from memcache...")
		memKeys = make([]string, size, size)
		for i := range dsKeys {
			memKeys[i] = ent.GetMemcacheKey(dsKeys[i])
		}
		err := memcache.GetMulti(ctx, memKeys, ents)
		if err == nil {
			// Hit caches on all keys!!
			return dsKeys, ents, nil
		}
		logger.Debug(func(p *xlog.Printer) {
			p.Println("Example#GetMulti [Memcache]")
			for i := 0; i < size; i++ {
				s := fmt.Sprintf("%v", ents[i])
				if len(s) > 20 {
					p.Printf("\t%s - %s...\n", memKeys[i], s[:20])
				} else {
					p.Printf("\t%s - %s\n", memKeys[i], s)
				}
				if i >= 20 {
					p.Printf("\t...(and %d ents)\n", size-i)
					break
				}
			}
		})
	}

	key2Idx := make(map[*datastore.Key]int)
	cacheMissingKeys := make([]*datastore.Key, 0)
	for i := range ents {
		if ents[i] == nil {
			key2Idx[dsKeys[i]] = i
			cacheMissingKeys = append(cacheMissingKeys, dsKeys[i])
		}
	}
	cacheMissingSize := len(cacheMissingKeys)

	// Datastore access
	cacheMissingEnts := make([]*Example, cacheMissingSize, cacheMissingSize)
	err := helper.GetMulti(ctx, cacheMissingKeys, cacheMissingEnts)
	if helper.IsDatastoreError(err) {
		// we return nil even some ents hits the cache.
		return nil, nil, err
	}

	if k.useDefaultIfNil {
		for i := 0; i < cacheMissingSize; i++ {
			if cacheMissingEnts[i] == nil {
				cacheMissingEnts[i] = NewExample()
				cacheMissingEnts[i].ID = dsKeys[i].StringID() // TODO: Support non-string key as ID
			}
		}
	}

	// merge cacheMissingEnts with ents.
	for i := range cacheMissingKeys {
		entIdx := key2Idx[cacheMissingKeys[i]]
		ents[entIdx] = cacheMissingEnts[i]
	}

	// create a cache
	if !k.noCache {
		cacheEnts := make([]*Example, 0)
		cacheKeys := make([]string, 0)
		for i := range ents {
			if ents[i] != nil {
				cacheEnts = append(cacheEnts, ents[i])
				cacheKeys = append(cacheKeys, memKeys[i])
			}
		}
		if len(cacheEnts) > 0 {
			if err := memcache.SetMulti(ctx, cacheKeys, cacheEnts); err != nil {
				logger.Warnf("Failed to create Example) caches: %v", err)
			}
		}
	}

	logger.Debug(func(p *xlog.Printer) {
		p.Printf(
			"Example#GetMulti [Datastore] (UseDefault: %t, NoCache: %t)\n",
			k.useDefaultIfNil, k.noCache,
		)
		for i := 0; i < size; i++ {
			s := fmt.Sprintf("%v", ents[i])
			if len(s) > 20 {
				p.Printf("\t%s - %s...\n", dsKeys[i], s[:20])
			} else {
				p.Printf("\t%s - %s\n", dsKeys[i], s)
			}
			if i >= 20 {
				p.Printf("\t...(and %d ents)\n", size-i)
				break
			}
		}
	})
	return dsKeys, ents, nil
}

// MustGetMulti is like GetMulti but returns only values and panic if error happens.
func (k *ExampleKind) MustGetMulti(ctx context.Context, keys ...interface{}) []*Example {
	_, v, err := k.GetMulti(ctx, keys...)
	if err != nil {
		panic(err)
	}
	return v
}

// Put puts the entity to datastore.
func (k *ExampleKind) Put(ctx context.Context, ent *Example) (*datastore.Key, error) {
	keys, err := k.PutMulti(ctx, []*Example{
		ent,
	})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

// MustPut is like Put and panic if an error occurrs.
func (k *ExampleKind) MustPut(ctx context.Context, ent *Example) *datastore.Key {
	keys, err := k.Put(ctx, ent)
	if err != nil {
		panic(err)
	}
	return keys
}

// PutMulti do Put with multiple keys
func (k *ExampleKind) PutMulti(ctx context.Context, ents []*Example) ([]*datastore.Key, error) {
	var size = len(ents)
	var dsKeys []*datastore.Key
	if size == 0 {
		return nil, nil
	}
	logger := xlog.WithContext(ctx).WithKey(ExampleKindLoggerKey)

	dsKeys = make([]*datastore.Key, size, size)
	for i := range ents {
		if k.BeforeSave != nil {
			if err := k.BeforeSave(ents[i]); err != nil {
				return nil, err
			}
		}
		dsKeys[i] = ents[i].NewKey(ctx)
	}

	if !k.noTimestampUpdate {
		for i := range ents {
			ents[i].UpdatedAt = xtime.Now()
		}
	}

	_, err := helper.PutMulti(ctx, dsKeys, ents)
	if helper.IsDatastoreError(err) {
		return nil, err
	}

	if !k.noCache {
		memKeys := make([]string, size, size)
		for i := range memKeys {
			memKeys[i] = ent.GetMemcacheKey(dsKeys[i])
		}
		err := memcache.DeleteMulti(ctx, memKeys)
		if memcache.IsMemcacheError(err) {
			logger.Warnf("Failed to invalidate memcache keys: %v", err)
		}
	}

	logger.Debug(func(p *xlog.Printer) {
		p.Printf(
			"Example#PutMulti [Datastore] (NoCache: %t)\n",
			k.noCache,
		)
		for i := 0; i < size; i++ {
			s := fmt.Sprintf("%v", ents[i])
			if len(s) > 20 {
				p.Printf("\t%s - %s...\n", dsKeys[i], s[:20])
			} else {
				p.Printf("\t%s - %s\n", dsKeys[i], s)
			}
			if i >= 20 {
				p.Printf("\t...(and %d ents)\n", size-i)
				break
			}
		}
	})

	return dsKeys, nil
}

// MustPutMulti do Put with multiple keys
func (k *ExampleKind) MustPutMulti(ctx context.Context, ents []*Example) []*datastore.Key {
	keys, err := k.PutMulti(ctx, ents)
	if err != nil {
		panic(err)
	}
	return keys
}

// ExampleQuery helps to build and execute a query
type ExampleQuery struct {
	q *helper.Query
}

func NewExampleQuery() *ExampleQuery {
	return &ExampleQuery{
		q: helper.NewQuery("Example"),
	}
}

// Ancestor sets the ancestor filter
func (q *ExampleQuery) Ancestor(a lazy.Value) *ExampleQuery {
	q.q = q.q.Ancestor(a)
	return q
}

// Eq sets the "=" filter on the name field.
func (q *ExampleQuery) Eq(name string, value lazy.Value) *ExampleQuery {
	q.q = q.q.Eq(name, value)
	return q
}

// Lt sets the "<" filter on the "name" field.
func (q *ExampleQuery) Lt(name string, value lazy.Value) *ExampleQuery {
	q.q = q.q.Lt(name, value)
	return q
}

// Le sets the "<=" filter on the "name" field.
func (q *ExampleQuery) Le(name string, value lazy.Value) *ExampleQuery {
	q.q = q.q.Le(name, value)
	return q
}

// Gt sets the ">" filter on the "name" field.
func (q *ExampleQuery) Gt(name string, value lazy.Value) *ExampleQuery {
	q.q = q.q.Gt(name, value)
	return q
}

// Ge sets the ">=" filter on the "name" field.
func (q *ExampleQuery) Ge(name string, value lazy.Value) *ExampleQuery {
	q.q = q.q.Ge(name, value)
	return q
}

// Ne sets the "!=" filter on the "name" field.
func (q *ExampleQuery) Ne(name string, value lazy.Value) *ExampleQuery {
	q.q = q.q.Ne(name, value)
	return q
}

// Asc specifies ascending order on the given filed.
func (q *ExampleQuery) Asc(name string) *ExampleQuery {
	q.q = q.q.Asc(name)
	return q
}

// Desc specifies descending order on the given filed.
func (q *ExampleQuery) Desc(name string) *ExampleQuery {
	q.q = q.q.Desc(name)
	return q
}

// GetAll returns all key and value of the query.
func (q *ExampleQuery) GetAll(ctx context.Context) ([]*datastore.Key, []*Example, error) {
	var v []*Example
	keys, err := q.q.GetAll(ctx, &v)
	if err != nil {
		return nil, nil, err
	}
	return keys, v, err
}

// MustGetAll is like GetAll but panic if an error occurrs.
func (q *ExampleQuery) MustGetAll(ctx context.Context) ([]*datastore.Key, []*Example) {
	keys, values, err := q.GetAll(ctx)
	if err != nil {
		panic(err)
	}
	return keys, values
}

// GetAllValues is like GetAll but returns only values
func (q *ExampleQuery) GetAllValues(ctx context.Context) ([]*Example, error) {
	var v []*Example
	_, err := q.q.GetAll(ctx, &v)
	if err != nil {
		return nil, err
	}
	return v, err
}

// MustGetAllValues is like GetAllValues but panic if an error occurrs
func (q *ExampleQuery) MustGetAllValues(ctx context.Context) []*Example {
	var v []*Example
	_, err := q.q.GetAll(ctx, &v)
	if err != nil {
		panic(err)
	}
	return v
}

// Count returns the count of entities
func (q *ExampleQuery) Count(ctx context.Context) (int, error) {
	return q.q.Count(ctx)
}

// MustCount returns the count of entities
func (q *ExampleQuery) MustCount(ctx context.Context) int {
	c, err := q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return c
}
