// Code generated by github.com/yssk22/go/generator DO NOT EDIT.
//
package config

import (
	"context"

	"cloud.google.com/go/datastore"
	ds "github.com/yssk22/go/gcp/datastore"
	"github.com/yssk22/go/x/xerrors"
	"github.com/yssk22/go/x/xtime"
	"google.golang.org/api/iterator"
)

func (s *ServiceConfig) NewKey(ctx context.Context) *datastore.Key {
	key := ds.NewKey("ServiceConfig", s.ID)
	key.Namespace = ""
	return key
}

type ServiceConfigReplacer interface {
	Replace(*ServiceConfig, *ServiceConfig) *ServiceConfig
}

type ServiceConfigReplacerFunc func(*ServiceConfig, *ServiceConfig) *ServiceConfig

func (f ServiceConfigReplacerFunc) Replace(old *ServiceConfig, new *ServiceConfig) *ServiceConfig {
	return f(old, new)
}

type ServiceConfigKindClient struct {
	client *ds.Client
}

func NewServiceConfigKindClient(client *ds.Client) *ServiceConfigKindClient {
	return &ServiceConfigKindClient{
		client: client,
	}
}

func (d *ServiceConfigKindClient) Get(ctx context.Context, key interface{}) (*datastore.Key, *ServiceConfig, error) {
	keys, ents, err := d.GetMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

func (d *ServiceConfigKindClient) MustGet(ctx context.Context, key interface{}) (*datastore.Key, *ServiceConfig) {
	k, v, e := d.Get(ctx, key)
	xerrors.MustNil(e)
	return k, v
}

func (d *ServiceConfigKindClient) GetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*ServiceConfig, error) {
	var err error
	var dsKeys []*datastore.Key
	var ents []*ServiceConfig
	if dsKeys, err = ds.NormalizeKeys(keys, "ServiceConfig", ""); err != nil {
		return nil, nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil, nil
	}
	ents = make([]*ServiceConfig, size, size)
	if err = d.client.GetMulti(ctx, dsKeys, ents); err != nil {
		return nil, nil, err
	}
	return dsKeys, ents, nil
}

func (d *ServiceConfigKindClient) MustGetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*ServiceConfig) {
	k, v, e := d.GetMulti(ctx, keys)
	xerrors.MustNil(e)
	return k, v
}

func (d *ServiceConfigKindClient) Put(ctx context.Context, ent *ServiceConfig) (*datastore.Key, error) {
	keys, err := d.PutMulti(ctx, []*ServiceConfig{ent})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *ServiceConfigKindClient) MustPut(ctx context.Context, ent *ServiceConfig) *datastore.Key {
	k, e := d.Put(ctx, ent)
	xerrors.MustNil(e)
	return k
}

func (d *ServiceConfigKindClient) PutMulti(ctx context.Context, ents []*ServiceConfig) ([]*datastore.Key, error) {
	var err error
	var size = len(ents)
	var dsKeys []*datastore.Key
	dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return nil, nil
	}
	_, hasBeforeSave := interface{}(ents[0]).(ds.BeforeSave)
	_, hasAfterSave := interface{}(ents[0]).(ds.AfterSave)

	if hasBeforeSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.BeforeSave).BeforeSave(ctx); err != nil {
				return nil, err
			}
		}
	}

	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
		ents[i].UpdatedAt = xtime.Now()
	}
	if dsKeys, err = d.client.PutMulti(ctx, dsKeys, ents); err != nil {
		return nil, err
	}

	if hasAfterSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.AfterSave).AfterSave(ctx); err != nil {
				return nil, err
			}
		}
	}
	return dsKeys, nil
}

func (d *ServiceConfigKindClient) MustPutMulti(ctx context.Context, ents []*ServiceConfig) []*datastore.Key {
	keys, err := d.PutMulti(ctx, ents)
	xerrors.MustNil(err)
	return keys
}

func (d *ServiceConfigKindClient) Delete(ctx context.Context, key interface{}) (*datastore.Key, error) {
	keys, err := d.DeleteMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *ServiceConfigKindClient) MustDelete(ctx context.Context, key interface{}) *datastore.Key {
	k, e := d.Delete(ctx, key)
	xerrors.MustNil(e)
	return k
}

func (d *ServiceConfigKindClient) DeleteMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, error) {
	var err error
	var dsKeys []*datastore.Key
	if dsKeys, err = ds.NormalizeKeys(keys, "ServiceConfig", ""); err != nil {
		return nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil
	}
	if err = d.client.DeleteMulti(ctx, dsKeys); err != nil {
		return nil, xerrors.Wrap(err, "datastore error")
	}
	return dsKeys, nil
}

func (d *ServiceConfigKindClient) MustDeleteMulti(ctx context.Context, keys interface{}) []*datastore.Key {
	k, e := d.DeleteMulti(ctx, keys)
	xerrors.MustNil(e)
	return k
}

func (d *ServiceConfigKindClient) DeleteMatched(ctx context.Context, q *ServiceConfigQuery) ([]*datastore.Key, error) {
	keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
	if err != nil {
		return nil, err
	}
	_, err = d.DeleteMulti(ctx, keys)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

func (d *ServiceConfigKindClient) MustDeleteMatched(ctx context.Context, q *ServiceConfigQuery) []*datastore.Key {
	keys, err := d.DeleteMatched(ctx, q)
	xerrors.MustNil(err)
	return keys
}

func (d *ServiceConfigKindClient) Replace(ctx context.Context, ent *ServiceConfig, replacer ServiceConfigReplacer) (*datastore.Key, *ServiceConfig, error) {
	keys, ents, err := d.ReplaceMulti(ctx, []*ServiceConfig{ent}, replacer)
	if err != nil {
		return nil, ents[0], err
	}
	return keys[0], ents[0], err
}

func (d *ServiceConfigKindClient) MustReplace(ctx context.Context, ent *ServiceConfig, replacer ServiceConfigReplacer) (*datastore.Key, *ServiceConfig) {
	k, v, e := d.Replace(ctx, ent, replacer)
	xerrors.MustNil(e)
	return k, v
}

func (d *ServiceConfigKindClient) ReplaceMulti(ctx context.Context, ents []*ServiceConfig, replacer ServiceConfigReplacer) ([]*datastore.Key, []*ServiceConfig, error) {
	var size = len(ents)
	var dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return dsKeys, ents, nil
	}
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
	}
	_, existing, err := d.GetMulti(ctx, dsKeys)
	if err != nil {
		return nil, ents, err
	}
	for i, exist := range existing {
		if exist != nil {
			ents[i] = replacer.Replace(exist, ents[i])
		}
	}
	dsKeys, err = d.PutMulti(ctx, ents)
	return dsKeys, ents, err
}

func (d *ServiceConfigKindClient) MustReplaceMulti(ctx context.Context, ents []*ServiceConfig, replacer ServiceConfigReplacer) ([]*datastore.Key, []*ServiceConfig) {
	k, v, e := d.ReplaceMulti(ctx, ents, replacer)
	xerrors.MustNil(e)
	return k, v
}

type ServiceConfigQuery struct {
	query   *ds.Query
	viaKeys bool
}

func NewServiceConfigQuery() *ServiceConfigQuery {
	return &ServiceConfigQuery{
		query:   ds.NewQuery("ServiceConfig").Namespace(""),
		viaKeys: false,
	}
}

func (d *ServiceConfigQuery) EqID(v string) *ServiceConfigQuery {
	d.query = d.query.Eq("ID", v)
	return d
}

func (d *ServiceConfigQuery) EqKey(v string) *ServiceConfigQuery {
	d.query = d.query.Eq("Key", v)
	return d
}

func (d *ServiceConfigQuery) LtID(v string) *ServiceConfigQuery {
	d.query = d.query.Lt("ID", v)
	return d
}

func (d *ServiceConfigQuery) LtKey(v string) *ServiceConfigQuery {
	d.query = d.query.Lt("Key", v)
	return d
}

func (d *ServiceConfigQuery) LeID(v string) *ServiceConfigQuery {
	d.query = d.query.Le("ID", v)
	return d
}

func (d *ServiceConfigQuery) LeKey(v string) *ServiceConfigQuery {
	d.query = d.query.Le("Key", v)
	return d
}

func (d *ServiceConfigQuery) GtID(v string) *ServiceConfigQuery {
	d.query = d.query.Gt("ID", v)
	return d
}

func (d *ServiceConfigQuery) GtKey(v string) *ServiceConfigQuery {
	d.query = d.query.Gt("Key", v)
	return d
}

func (d *ServiceConfigQuery) GeID(v string) *ServiceConfigQuery {
	d.query = d.query.Ge("ID", v)
	return d
}

func (d *ServiceConfigQuery) GeKey(v string) *ServiceConfigQuery {
	d.query = d.query.Ge("Key", v)
	return d
}

func (d *ServiceConfigQuery) NeID(v string) *ServiceConfigQuery {
	d.query = d.query.Ne("ID", v)
	return d
}

func (d *ServiceConfigQuery) NeKey(v string) *ServiceConfigQuery {
	d.query = d.query.Ne("Key", v)
	return d
}

func (d *ServiceConfigQuery) AscID() *ServiceConfigQuery {
	d.query = d.query.Asc("ID")
	return d
}

func (d *ServiceConfigQuery) AscKey() *ServiceConfigQuery {
	d.query = d.query.Asc("Key")
	return d
}

func (d *ServiceConfigQuery) DescID() *ServiceConfigQuery {
	d.query = d.query.Desc("ID")
	return d
}

func (d *ServiceConfigQuery) DescKey() *ServiceConfigQuery {
	d.query = d.query.Desc("Key")
	return d
}

func (q *ServiceConfigQuery) Start(s string) *ServiceConfigQuery {
	q.query = q.query.Start(s)
	return q
}

func (q *ServiceConfigQuery) End(s string) *ServiceConfigQuery {
	q.query = q.query.End(s)
	return q
}

func (q *ServiceConfigQuery) Limit(n int) *ServiceConfigQuery {
	q.query = q.query.Limit(n)
	return q
}

func (q *ServiceConfigQuery) ViaKeys() *ServiceConfigQuery {
	q.viaKeys = true
	return q
}

func (d *ServiceConfigKindClient) GetAll(ctx context.Context, q *ServiceConfigQuery) ([]*datastore.Key, []ServiceConfig, error) {
	if q.viaKeys {
		keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
		if err != nil {
			return nil, nil, err
		}
		ents := make([]*ServiceConfig, len(keys))
		err = d.client.GetMulti(ctx, keys, ents)
		if err != nil {
			return nil, nil, err
		}
		result := make([]ServiceConfig, 0)
		for _, e := range ents {
			if e != nil {
				result = append(result, *e)
			}
		}
		return keys, result, nil
	} else {
		var ent []ServiceConfig
		keys, err := d.client.GetAll(ctx, q.query, &ent)
		if err != nil {
			return nil, nil, err
		}
		return keys, ent, nil
	}
}

func (d *ServiceConfigKindClient) GetOne(ctx context.Context, q *ServiceConfigQuery) (*datastore.Key, *ServiceConfig, error) {
	keys, ents, err := d.GetAll(ctx, q.Limit(1))
	if err != nil {
		return nil, nil, err
	}
	if len(keys) == 0 {
		return nil, nil, nil
	}
	return keys[0], &(ents[0]), nil
}

func (d *ServiceConfigKindClient) MustGetAll(ctx context.Context, q *ServiceConfigQuery) ([]*datastore.Key, []ServiceConfig) {
	keys, ents, err := d.GetAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents
}

func (d *ServiceConfigKindClient) Count(ctx context.Context, q *ServiceConfigQuery) (int, error) {
	return d.client.Count(ctx, q.query)
}

func (d *ServiceConfigKindClient) MustCount(ctx context.Context, q *ServiceConfigQuery) int {
	c, err := d.Count(ctx, q)
	xerrors.MustNil(err)
	return c
}

func (d *ServiceConfigKindClient) Run(ctx context.Context, q *ServiceConfigQuery) (*ServiceConfigIterator, error) {
	iter, err := d.client.Run(ctx, q.query)
	if err != nil {
		return nil, err
	}
	return &ServiceConfigIterator{
		ctx:     ctx,
		iter:    iter,
		viaKeys: q.viaKeys,
		client:  d,
	}, err
}

func (d *ServiceConfigKindClient) MustRun(ctx context.Context, q *ServiceConfigQuery) *ServiceConfigIterator {
	iter, err := d.Run(ctx, q)
	xerrors.MustNil(err)
	return iter
}

func (d *ServiceConfigKindClient) RunAll(ctx context.Context, q *ServiceConfigQuery) ([]datastore.Key, []ServiceConfig, string, error) {
	iter, err := d.Run(ctx, q)
	if err != nil {
		return nil, nil, "", err
	}
	var keys []datastore.Key
	var ents []ServiceConfig
	for {
		key, ent, err := iter.Next()
		if err != nil {
			return nil, nil, "", err
		}
		if ent == nil {
			cursor, err := iter.iter.Cursor()
			if err != nil {
				return nil, nil, "", err
			}
			return keys, ents, cursor.String(), nil
		}
		keys = append(keys, *key)
		ents = append(ents, *ent)
	}
}

func (d *ServiceConfigKindClient) MustRunAll(ctx context.Context, q *ServiceConfigQuery) ([]datastore.Key, []ServiceConfig, string) {
	keys, ents, next, err := d.RunAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents, next
}

type ServiceConfigIterator struct {
	ctx     context.Context
	iter    *datastore.Iterator
	viaKeys bool
	client  *ServiceConfigKindClient
}

func (iter *ServiceConfigIterator) Cursor() (datastore.Cursor, error) {
	return iter.iter.Cursor()
}

func (iter *ServiceConfigIterator) MustCursor() datastore.Cursor {
	c, err := iter.iter.Cursor()
	xerrors.MustNil(err)
	return c
}

func (iter *ServiceConfigIterator) Next() (*datastore.Key, *ServiceConfig, error) {
	if iter.viaKeys {
		key, err := iter.iter.Next(nil)
		if err != nil {
			if err == iterator.Done {
				return nil, nil, nil
			}
			return nil, nil, err
		}
		_, ent, err := iter.client.Get(iter.ctx, key)
		if err != nil {
			return nil, nil, err
		}
		return key, ent, nil
	}
	var ent ServiceConfig
	key, err := iter.iter.Next(&ent)
	if err != nil {
		if err == iterator.Done {
			return nil, nil, nil
		}
		return nil, nil, err
	}
	return key, &ent, nil
}

func (iter *ServiceConfigIterator) MustNext() (*datastore.Key, *ServiceConfig) {
	key, ent, err := iter.Next()
	xerrors.MustNil(err)
	return key, ent
}
