// Package ent provides utility functions for code generated by ent tool
package ent

import (
	"fmt"

	"google.golang.org/appengine/datastore"
)

// LoggerKey is a key of logger in this package.
const LoggerKey = "gae.datastore.ent"

// GetMemcacheKey returns memcache key correspoding to *datastore.Key
// "datastore.{namespace}.{kind}.{StringID|IntID}" is used.
func GetMemcacheKey(k *datastore.Key) string {
	if k.StringID() != "" {
		return fmt.Sprintf("datastore.%s.%s", k.Kind(), k.StringID())
	}
	return fmt.Sprintf("datastore.%s.%s", k.Kind(), k.IntID())
}
