version: 2.0
jobs:
  build:
    docker:
      - image: speedland/circle-ci-gae:latest
    working_directory: /go/src/github.com/speedland/go

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout
      - run: mkdir -p ${TEST_RESULTS}
      - run:
          name: Install Dependencies
          command: |
            go get ./...
      - run:
          name: Unit Tests
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test ./... | tee ${TEST_RESULTS}/go-test.out
      - store_test_results:
          path: /tmp/test-results
