version: 2
jobs:
    checkout_code:
        docker:
            - image: circleci/golang:1.12.5
        working_directory: ~/project
        steps:
            - checkout
            - save_cache:
                  key: repo-{{ .Environment.CIRCLE_SHA1 }}
                  paths:
                      - ~/project
    go-test:
        docker:
            - image: yssk22/circle-ci:latest
        working_directory: ~/project
        steps:
            - restore_cache:
                  name: Repo Cache
                  key: repo-{{ .Environment.CIRCLE_SHA1 }}
            - restore_cache:
                  name: Go Module Cache
                  key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum go.mod" }}
            - run:
                  name: Run Makefile
                  command: |
                      make go-test
            - save_cache:
                  name: Save Go Module Cache
                  key: mod-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "go.mod" }}
                  paths:
                      - /go/pkg/mod/cache
    update_master:
        docker:
            - image: circleci/golang:1.12.5
        working_directory: ~/project
        steps:
            - restore_cache:
                  name: Repo Cache
                  key: repo-{{ .Environment.CIRCLE_SHA1 }}
            - run:
                  name: Add github to knwon_hosts
                  command: |
                      mkdir -p ~/.ssh
                      cat keys/known_hosts >> ~/.ssh/known_hosts
            - run:
                  name: Merge master (site)
                  command: |
                      git config --global user.name "yssk22"
                      git config --global user.email "yssk22@gmail.com"
                      git branch -D master
                      git fetch origin master
                      git checkout master
                      git merge origin/master
                      git merge develop --no-ff -m "Merge 'develop' (CI auto merge)"
                      git push origin master
workflows:
    version: 2
    test:
        jobs:
            - checkout_code
            - go-test:
                  requires:
                      - checkout_code
            - update_master:
                  requires:
                      - go-test
                  filters:
                      branches:
                          only:
                              - develop
