// Code generated by github.com/yssk22/go/generator DO NOT EDIT.
//
package counter

import (
	"context"
	"time"

	"cloud.google.com/go/datastore"
	ds "github.com/yssk22/go/gcp/datastore"
	"github.com/yssk22/go/x/xerrors"
	"github.com/yssk22/go/x/xtime"
	"google.golang.org/api/iterator"
)

func (s *Config) NewKey(ctx context.Context) *datastore.Key {
	key := ds.NewKey("CounterConfig", s.Key)
	key.Namespace = ""
	return key
}

type ConfigReplacer interface {
	Replace(*Config, *Config) *Config
}

type ConfigReplacerFunc func(*Config, *Config) *Config

func (f ConfigReplacerFunc) Replace(old *Config, new *Config) *Config {
	return f(old, new)
}

type ConfigKindClient struct {
	client *ds.Client
}

func NewConfigKindClient(client *ds.Client) *ConfigKindClient {
	return &ConfigKindClient{
		client: client,
	}
}

func (d *ConfigKindClient) Get(ctx context.Context, key interface{}) (*datastore.Key, *Config, error) {
	keys, ents, err := d.GetMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

func (d *ConfigKindClient) MustGet(ctx context.Context, key interface{}) (*datastore.Key, *Config) {
	k, v, e := d.Get(ctx, key)
	xerrors.MustNil(e)
	return k, v
}

func (d *ConfigKindClient) GetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*Config, error) {
	var err error
	var dsKeys []*datastore.Key
	var ents []*Config
	if dsKeys, err = ds.NormalizeKeys(keys, "CounterConfig", ""); err != nil {
		return nil, nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil, nil
	}
	ents = make([]*Config, size, size)
	if err = d.client.GetMulti(ctx, dsKeys, ents); err != nil {
		return nil, nil, err
	}
	return dsKeys, ents, nil
}

func (d *ConfigKindClient) MustGetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*Config) {
	k, v, e := d.GetMulti(ctx, keys)
	xerrors.MustNil(e)
	return k, v
}

func (d *ConfigKindClient) Put(ctx context.Context, ent *Config) (*datastore.Key, error) {
	keys, err := d.PutMulti(ctx, []*Config{ent})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *ConfigKindClient) MustPut(ctx context.Context, ent *Config) *datastore.Key {
	k, e := d.Put(ctx, ent)
	xerrors.MustNil(e)
	return k
}

func (d *ConfigKindClient) PutMulti(ctx context.Context, ents []*Config) ([]*datastore.Key, error) {
	var err error
	var size = len(ents)
	var dsKeys []*datastore.Key
	dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return nil, nil
	}
	_, hasBeforeSave := interface{}(ents[0]).(ds.BeforeSave)
	_, hasAfterSave := interface{}(ents[0]).(ds.AfterSave)

	if hasBeforeSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.BeforeSave).BeforeSave(ctx); err != nil {
				return nil, err
			}
		}
	}

	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
		ents[i].UpdatedAt = xtime.Now()
	}
	if dsKeys, err = d.client.PutMulti(ctx, dsKeys, ents); err != nil {
		return nil, err
	}

	if hasAfterSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.AfterSave).AfterSave(ctx); err != nil {
				return nil, err
			}
		}
	}
	return dsKeys, nil
}

func (d *ConfigKindClient) MustPutMulti(ctx context.Context, ents []*Config) []*datastore.Key {
	keys, err := d.PutMulti(ctx, ents)
	xerrors.MustNil(err)
	return keys
}

func (d *ConfigKindClient) Delete(ctx context.Context, key interface{}) (*datastore.Key, error) {
	keys, err := d.DeleteMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *ConfigKindClient) MustDelete(ctx context.Context, key interface{}) *datastore.Key {
	k, e := d.Delete(ctx, key)
	xerrors.MustNil(e)
	return k
}

func (d *ConfigKindClient) DeleteMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, error) {
	var err error
	var dsKeys []*datastore.Key
	if dsKeys, err = ds.NormalizeKeys(keys, "CounterConfig", ""); err != nil {
		return nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil
	}
	if err = d.client.DeleteMulti(ctx, dsKeys); err != nil {
		return nil, xerrors.Wrap(err, "datastore error")
	}
	return dsKeys, nil
}

func (d *ConfigKindClient) MustDeleteMulti(ctx context.Context, keys interface{}) []*datastore.Key {
	k, e := d.DeleteMulti(ctx, keys)
	xerrors.MustNil(e)
	return k
}

func (d *ConfigKindClient) DeleteMatched(ctx context.Context, q *ConfigQuery) ([]*datastore.Key, error) {
	keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
	if err != nil {
		return nil, err
	}
	_, err = d.DeleteMulti(ctx, keys)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

func (d *ConfigKindClient) MustDeleteMatched(ctx context.Context, q *ConfigQuery) []*datastore.Key {
	keys, err := d.DeleteMatched(ctx, q)
	xerrors.MustNil(err)
	return keys
}

func (d *ConfigKindClient) Replace(ctx context.Context, ent *Config, replacer ConfigReplacer) (*datastore.Key, *Config, error) {
	keys, ents, err := d.ReplaceMulti(ctx, []*Config{ent}, replacer)
	if err != nil {
		return nil, ents[0], err
	}
	return keys[0], ents[0], err
}

func (d *ConfigKindClient) MustReplace(ctx context.Context, ent *Config, replacer ConfigReplacer) (*datastore.Key, *Config) {
	k, v, e := d.Replace(ctx, ent, replacer)
	xerrors.MustNil(e)
	return k, v
}

func (d *ConfigKindClient) ReplaceMulti(ctx context.Context, ents []*Config, replacer ConfigReplacer) ([]*datastore.Key, []*Config, error) {
	var size = len(ents)
	var dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return dsKeys, ents, nil
	}
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
	}
	_, existing, err := d.GetMulti(ctx, dsKeys)
	if err != nil {
		return nil, ents, err
	}
	for i, exist := range existing {
		if exist != nil {
			ents[i] = replacer.Replace(exist, ents[i])
		}
	}
	dsKeys, err = d.PutMulti(ctx, ents)
	return dsKeys, ents, err
}

func (d *ConfigKindClient) MustReplaceMulti(ctx context.Context, ents []*Config, replacer ConfigReplacer) ([]*datastore.Key, []*Config) {
	k, v, e := d.ReplaceMulti(ctx, ents, replacer)
	xerrors.MustNil(e)
	return k, v
}

type ConfigQuery struct {
	query   *ds.Query
	viaKeys bool
}

func NewConfigQuery() *ConfigQuery {
	return &ConfigQuery{
		query:   ds.NewQuery("CounterConfig").Namespace(""),
		viaKeys: false,
	}
}

func (d *ConfigQuery) EqKey(v string) *ConfigQuery {
	d.query = d.query.Eq("Key", v)
	return d
}

func (d *ConfigQuery) EqNumShards(v int) *ConfigQuery {
	d.query = d.query.Eq("NumShards", v)
	return d
}

func (d *ConfigQuery) EqUpdatedAt(v time.Time) *ConfigQuery {
	d.query = d.query.Eq("UpdatedAt", v)
	return d
}

func (d *ConfigQuery) LtKey(v string) *ConfigQuery {
	d.query = d.query.Lt("Key", v)
	return d
}

func (d *ConfigQuery) LtNumShards(v int) *ConfigQuery {
	d.query = d.query.Lt("NumShards", v)
	return d
}

func (d *ConfigQuery) LtUpdatedAt(v time.Time) *ConfigQuery {
	d.query = d.query.Lt("UpdatedAt", v)
	return d
}

func (d *ConfigQuery) LeKey(v string) *ConfigQuery {
	d.query = d.query.Le("Key", v)
	return d
}

func (d *ConfigQuery) LeNumShards(v int) *ConfigQuery {
	d.query = d.query.Le("NumShards", v)
	return d
}

func (d *ConfigQuery) LeUpdatedAt(v time.Time) *ConfigQuery {
	d.query = d.query.Le("UpdatedAt", v)
	return d
}

func (d *ConfigQuery) GtKey(v string) *ConfigQuery {
	d.query = d.query.Gt("Key", v)
	return d
}

func (d *ConfigQuery) GtNumShards(v int) *ConfigQuery {
	d.query = d.query.Gt("NumShards", v)
	return d
}

func (d *ConfigQuery) GtUpdatedAt(v time.Time) *ConfigQuery {
	d.query = d.query.Gt("UpdatedAt", v)
	return d
}

func (d *ConfigQuery) GeKey(v string) *ConfigQuery {
	d.query = d.query.Ge("Key", v)
	return d
}

func (d *ConfigQuery) GeNumShards(v int) *ConfigQuery {
	d.query = d.query.Ge("NumShards", v)
	return d
}

func (d *ConfigQuery) GeUpdatedAt(v time.Time) *ConfigQuery {
	d.query = d.query.Ge("UpdatedAt", v)
	return d
}

func (d *ConfigQuery) NeKey(v string) *ConfigQuery {
	d.query = d.query.Ne("Key", v)
	return d
}

func (d *ConfigQuery) NeNumShards(v int) *ConfigQuery {
	d.query = d.query.Ne("NumShards", v)
	return d
}

func (d *ConfigQuery) NeUpdatedAt(v time.Time) *ConfigQuery {
	d.query = d.query.Ne("UpdatedAt", v)
	return d
}

func (d *ConfigQuery) AscKey() *ConfigQuery {
	d.query = d.query.Asc("Key")
	return d
}

func (d *ConfigQuery) AscNumShards() *ConfigQuery {
	d.query = d.query.Asc("NumShards")
	return d
}

func (d *ConfigQuery) AscUpdatedAt() *ConfigQuery {
	d.query = d.query.Asc("UpdatedAt")
	return d
}

func (d *ConfigQuery) DescKey() *ConfigQuery {
	d.query = d.query.Desc("Key")
	return d
}

func (d *ConfigQuery) DescNumShards() *ConfigQuery {
	d.query = d.query.Desc("NumShards")
	return d
}

func (d *ConfigQuery) DescUpdatedAt() *ConfigQuery {
	d.query = d.query.Desc("UpdatedAt")
	return d
}

func (q *ConfigQuery) Start(s string) *ConfigQuery {
	q.query = q.query.Start(s)
	return q
}

func (q *ConfigQuery) End(s string) *ConfigQuery {
	q.query = q.query.End(s)
	return q
}

func (q *ConfigQuery) Limit(n int) *ConfigQuery {
	q.query = q.query.Limit(n)
	return q
}

func (q *ConfigQuery) ViaKeys() *ConfigQuery {
	q.viaKeys = true
	return q
}

func (d *ConfigKindClient) GetAll(ctx context.Context, q *ConfigQuery) ([]*datastore.Key, []Config, error) {
	if q.viaKeys {
		keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
		if err != nil {
			return nil, nil, err
		}
		ents := make([]*Config, len(keys))
		err = d.client.GetMulti(ctx, keys, ents)
		if err != nil {
			return nil, nil, err
		}
		result := make([]Config, 0)
		for _, e := range ents {
			if e != nil {
				result = append(result, *e)
			}
		}
		return keys, result, nil
	} else {
		var ent []Config
		keys, err := d.client.GetAll(ctx, q.query, &ent)
		if err != nil {
			return nil, nil, err
		}
		return keys, ent, nil
	}
}

func (d *ConfigKindClient) GetOne(ctx context.Context, q *ConfigQuery) (*datastore.Key, *Config, error) {
	keys, ents, err := d.GetAll(ctx, q.Limit(1))
	if err != nil {
		return nil, nil, err
	}
	if len(keys) == 0 {
		return nil, nil, nil
	}
	return keys[0], &(ents[0]), nil
}

func (d *ConfigKindClient) MustGetAll(ctx context.Context, q *ConfigQuery) ([]*datastore.Key, []Config) {
	keys, ents, err := d.GetAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents
}

func (d *ConfigKindClient) Count(ctx context.Context, q *ConfigQuery) (int, error) {
	return d.client.Count(ctx, q.query)
}

func (d *ConfigKindClient) MustCount(ctx context.Context, q *ConfigQuery) int {
	c, err := d.Count(ctx, q)
	xerrors.MustNil(err)
	return c
}

func (d *ConfigKindClient) Run(ctx context.Context, q *ConfigQuery) (*ConfigIterator, error) {
	iter, err := d.client.Run(ctx, q.query)
	if err != nil {
		return nil, err
	}
	return &ConfigIterator{
		ctx:     ctx,
		iter:    iter,
		viaKeys: q.viaKeys,
		client:  d,
	}, err
}

func (d *ConfigKindClient) MustRun(ctx context.Context, q *ConfigQuery) *ConfigIterator {
	iter, err := d.Run(ctx, q)
	xerrors.MustNil(err)
	return iter
}

func (d *ConfigKindClient) RunAll(ctx context.Context, q *ConfigQuery) ([]datastore.Key, []Config, string, error) {
	iter, err := d.Run(ctx, q)
	if err != nil {
		return nil, nil, "", err
	}
	var keys []datastore.Key
	var ents []Config
	for {
		key, ent, err := iter.Next()
		if err != nil {
			return nil, nil, "", err
		}
		if ent == nil {
			cursor, err := iter.iter.Cursor()
			if err != nil {
				return nil, nil, "", err
			}
			return keys, ents, cursor.String(), nil
		}
		keys = append(keys, *key)
		ents = append(ents, *ent)
	}
}

func (d *ConfigKindClient) MustRunAll(ctx context.Context, q *ConfigQuery) ([]datastore.Key, []Config, string) {
	keys, ents, next, err := d.RunAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents, next
}

type ConfigIterator struct {
	ctx     context.Context
	iter    *datastore.Iterator
	viaKeys bool
	client  *ConfigKindClient
}

func (iter *ConfigIterator) Cursor() (datastore.Cursor, error) {
	return iter.iter.Cursor()
}

func (iter *ConfigIterator) MustCursor() datastore.Cursor {
	c, err := iter.iter.Cursor()
	xerrors.MustNil(err)
	return c
}

func (iter *ConfigIterator) Next() (*datastore.Key, *Config, error) {
	if iter.viaKeys {
		key, err := iter.iter.Next(nil)
		if err != nil {
			if err == iterator.Done {
				return nil, nil, nil
			}
			return nil, nil, err
		}
		_, ent, err := iter.client.Get(iter.ctx, key)
		if err != nil {
			return nil, nil, err
		}
		return key, ent, nil
	}
	var ent Config
	key, err := iter.iter.Next(&ent)
	if err != nil {
		if err == iterator.Done {
			return nil, nil, nil
		}
		return nil, nil, err
	}
	return key, &ent, nil
}

func (iter *ConfigIterator) MustNext() (*datastore.Key, *Config) {
	key, ent, err := iter.Next()
	xerrors.MustNil(err)
	return key, ent
}

func (s *Shard) NewKey(ctx context.Context) *datastore.Key {
	key := ds.NewKey("CounterShard", s.Key)
	key.Namespace = ""
	return key
}

type ShardReplacer interface {
	Replace(*Shard, *Shard) *Shard
}

type ShardReplacerFunc func(*Shard, *Shard) *Shard

func (f ShardReplacerFunc) Replace(old *Shard, new *Shard) *Shard {
	return f(old, new)
}

type ShardKindClient struct {
	client *ds.Client
}

func NewShardKindClient(client *ds.Client) *ShardKindClient {
	return &ShardKindClient{
		client: client,
	}
}

func (d *ShardKindClient) Get(ctx context.Context, key interface{}) (*datastore.Key, *Shard, error) {
	keys, ents, err := d.GetMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

func (d *ShardKindClient) MustGet(ctx context.Context, key interface{}) (*datastore.Key, *Shard) {
	k, v, e := d.Get(ctx, key)
	xerrors.MustNil(e)
	return k, v
}

func (d *ShardKindClient) GetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*Shard, error) {
	var err error
	var dsKeys []*datastore.Key
	var ents []*Shard
	if dsKeys, err = ds.NormalizeKeys(keys, "CounterShard", ""); err != nil {
		return nil, nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil, nil
	}
	ents = make([]*Shard, size, size)
	if err = d.client.GetMulti(ctx, dsKeys, ents); err != nil {
		return nil, nil, err
	}
	return dsKeys, ents, nil
}

func (d *ShardKindClient) MustGetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*Shard) {
	k, v, e := d.GetMulti(ctx, keys)
	xerrors.MustNil(e)
	return k, v
}

func (d *ShardKindClient) Put(ctx context.Context, ent *Shard) (*datastore.Key, error) {
	keys, err := d.PutMulti(ctx, []*Shard{ent})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *ShardKindClient) MustPut(ctx context.Context, ent *Shard) *datastore.Key {
	k, e := d.Put(ctx, ent)
	xerrors.MustNil(e)
	return k
}

func (d *ShardKindClient) PutMulti(ctx context.Context, ents []*Shard) ([]*datastore.Key, error) {
	var err error
	var size = len(ents)
	var dsKeys []*datastore.Key
	dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return nil, nil
	}
	_, hasBeforeSave := interface{}(ents[0]).(ds.BeforeSave)
	_, hasAfterSave := interface{}(ents[0]).(ds.AfterSave)

	if hasBeforeSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.BeforeSave).BeforeSave(ctx); err != nil {
				return nil, err
			}
		}
	}

	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
		ents[i].UpdatedAt = xtime.Now()
	}
	if dsKeys, err = d.client.PutMulti(ctx, dsKeys, ents); err != nil {
		return nil, err
	}

	if hasAfterSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.AfterSave).AfterSave(ctx); err != nil {
				return nil, err
			}
		}
	}
	return dsKeys, nil
}

func (d *ShardKindClient) MustPutMulti(ctx context.Context, ents []*Shard) []*datastore.Key {
	keys, err := d.PutMulti(ctx, ents)
	xerrors.MustNil(err)
	return keys
}

func (d *ShardKindClient) Delete(ctx context.Context, key interface{}) (*datastore.Key, error) {
	keys, err := d.DeleteMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *ShardKindClient) MustDelete(ctx context.Context, key interface{}) *datastore.Key {
	k, e := d.Delete(ctx, key)
	xerrors.MustNil(e)
	return k
}

func (d *ShardKindClient) DeleteMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, error) {
	var err error
	var dsKeys []*datastore.Key
	if dsKeys, err = ds.NormalizeKeys(keys, "CounterShard", ""); err != nil {
		return nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil
	}
	if err = d.client.DeleteMulti(ctx, dsKeys); err != nil {
		return nil, xerrors.Wrap(err, "datastore error")
	}
	return dsKeys, nil
}

func (d *ShardKindClient) MustDeleteMulti(ctx context.Context, keys interface{}) []*datastore.Key {
	k, e := d.DeleteMulti(ctx, keys)
	xerrors.MustNil(e)
	return k
}

func (d *ShardKindClient) DeleteMatched(ctx context.Context, q *ShardQuery) ([]*datastore.Key, error) {
	keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
	if err != nil {
		return nil, err
	}
	_, err = d.DeleteMulti(ctx, keys)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

func (d *ShardKindClient) MustDeleteMatched(ctx context.Context, q *ShardQuery) []*datastore.Key {
	keys, err := d.DeleteMatched(ctx, q)
	xerrors.MustNil(err)
	return keys
}

func (d *ShardKindClient) Replace(ctx context.Context, ent *Shard, replacer ShardReplacer) (*datastore.Key, *Shard, error) {
	keys, ents, err := d.ReplaceMulti(ctx, []*Shard{ent}, replacer)
	if err != nil {
		return nil, ents[0], err
	}
	return keys[0], ents[0], err
}

func (d *ShardKindClient) MustReplace(ctx context.Context, ent *Shard, replacer ShardReplacer) (*datastore.Key, *Shard) {
	k, v, e := d.Replace(ctx, ent, replacer)
	xerrors.MustNil(e)
	return k, v
}

func (d *ShardKindClient) ReplaceMulti(ctx context.Context, ents []*Shard, replacer ShardReplacer) ([]*datastore.Key, []*Shard, error) {
	var size = len(ents)
	var dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return dsKeys, ents, nil
	}
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
	}
	_, existing, err := d.GetMulti(ctx, dsKeys)
	if err != nil {
		return nil, ents, err
	}
	for i, exist := range existing {
		if exist != nil {
			ents[i] = replacer.Replace(exist, ents[i])
		}
	}
	dsKeys, err = d.PutMulti(ctx, ents)
	return dsKeys, ents, err
}

func (d *ShardKindClient) MustReplaceMulti(ctx context.Context, ents []*Shard, replacer ShardReplacer) ([]*datastore.Key, []*Shard) {
	k, v, e := d.ReplaceMulti(ctx, ents, replacer)
	xerrors.MustNil(e)
	return k, v
}

type ShardQuery struct {
	query   *ds.Query
	viaKeys bool
}

func NewShardQuery() *ShardQuery {
	return &ShardQuery{
		query:   ds.NewQuery("CounterShard").Namespace(""),
		viaKeys: false,
	}
}

func (d *ShardQuery) EqKey(v string) *ShardQuery {
	d.query = d.query.Eq("Key", v)
	return d
}

func (d *ShardQuery) EqCounterKey(v string) *ShardQuery {
	d.query = d.query.Eq("CounterKey", v)
	return d
}

func (d *ShardQuery) EqCount(v int) *ShardQuery {
	d.query = d.query.Eq("Count", v)
	return d
}

func (d *ShardQuery) EqUpdatedAt(v time.Time) *ShardQuery {
	d.query = d.query.Eq("UpdatedAt", v)
	return d
}

func (d *ShardQuery) LtKey(v string) *ShardQuery {
	d.query = d.query.Lt("Key", v)
	return d
}

func (d *ShardQuery) LtCounterKey(v string) *ShardQuery {
	d.query = d.query.Lt("CounterKey", v)
	return d
}

func (d *ShardQuery) LtCount(v int) *ShardQuery {
	d.query = d.query.Lt("Count", v)
	return d
}

func (d *ShardQuery) LtUpdatedAt(v time.Time) *ShardQuery {
	d.query = d.query.Lt("UpdatedAt", v)
	return d
}

func (d *ShardQuery) LeKey(v string) *ShardQuery {
	d.query = d.query.Le("Key", v)
	return d
}

func (d *ShardQuery) LeCounterKey(v string) *ShardQuery {
	d.query = d.query.Le("CounterKey", v)
	return d
}

func (d *ShardQuery) LeCount(v int) *ShardQuery {
	d.query = d.query.Le("Count", v)
	return d
}

func (d *ShardQuery) LeUpdatedAt(v time.Time) *ShardQuery {
	d.query = d.query.Le("UpdatedAt", v)
	return d
}

func (d *ShardQuery) GtKey(v string) *ShardQuery {
	d.query = d.query.Gt("Key", v)
	return d
}

func (d *ShardQuery) GtCounterKey(v string) *ShardQuery {
	d.query = d.query.Gt("CounterKey", v)
	return d
}

func (d *ShardQuery) GtCount(v int) *ShardQuery {
	d.query = d.query.Gt("Count", v)
	return d
}

func (d *ShardQuery) GtUpdatedAt(v time.Time) *ShardQuery {
	d.query = d.query.Gt("UpdatedAt", v)
	return d
}

func (d *ShardQuery) GeKey(v string) *ShardQuery {
	d.query = d.query.Ge("Key", v)
	return d
}

func (d *ShardQuery) GeCounterKey(v string) *ShardQuery {
	d.query = d.query.Ge("CounterKey", v)
	return d
}

func (d *ShardQuery) GeCount(v int) *ShardQuery {
	d.query = d.query.Ge("Count", v)
	return d
}

func (d *ShardQuery) GeUpdatedAt(v time.Time) *ShardQuery {
	d.query = d.query.Ge("UpdatedAt", v)
	return d
}

func (d *ShardQuery) NeKey(v string) *ShardQuery {
	d.query = d.query.Ne("Key", v)
	return d
}

func (d *ShardQuery) NeCounterKey(v string) *ShardQuery {
	d.query = d.query.Ne("CounterKey", v)
	return d
}

func (d *ShardQuery) NeCount(v int) *ShardQuery {
	d.query = d.query.Ne("Count", v)
	return d
}

func (d *ShardQuery) NeUpdatedAt(v time.Time) *ShardQuery {
	d.query = d.query.Ne("UpdatedAt", v)
	return d
}

func (d *ShardQuery) AscKey() *ShardQuery {
	d.query = d.query.Asc("Key")
	return d
}

func (d *ShardQuery) AscCounterKey() *ShardQuery {
	d.query = d.query.Asc("CounterKey")
	return d
}

func (d *ShardQuery) AscCount() *ShardQuery {
	d.query = d.query.Asc("Count")
	return d
}

func (d *ShardQuery) AscUpdatedAt() *ShardQuery {
	d.query = d.query.Asc("UpdatedAt")
	return d
}

func (d *ShardQuery) DescKey() *ShardQuery {
	d.query = d.query.Desc("Key")
	return d
}

func (d *ShardQuery) DescCounterKey() *ShardQuery {
	d.query = d.query.Desc("CounterKey")
	return d
}

func (d *ShardQuery) DescCount() *ShardQuery {
	d.query = d.query.Desc("Count")
	return d
}

func (d *ShardQuery) DescUpdatedAt() *ShardQuery {
	d.query = d.query.Desc("UpdatedAt")
	return d
}

func (q *ShardQuery) Start(s string) *ShardQuery {
	q.query = q.query.Start(s)
	return q
}

func (q *ShardQuery) End(s string) *ShardQuery {
	q.query = q.query.End(s)
	return q
}

func (q *ShardQuery) Limit(n int) *ShardQuery {
	q.query = q.query.Limit(n)
	return q
}

func (q *ShardQuery) ViaKeys() *ShardQuery {
	q.viaKeys = true
	return q
}

func (d *ShardKindClient) GetAll(ctx context.Context, q *ShardQuery) ([]*datastore.Key, []Shard, error) {
	if q.viaKeys {
		keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
		if err != nil {
			return nil, nil, err
		}
		ents := make([]*Shard, len(keys))
		err = d.client.GetMulti(ctx, keys, ents)
		if err != nil {
			return nil, nil, err
		}
		result := make([]Shard, 0)
		for _, e := range ents {
			if e != nil {
				result = append(result, *e)
			}
		}
		return keys, result, nil
	} else {
		var ent []Shard
		keys, err := d.client.GetAll(ctx, q.query, &ent)
		if err != nil {
			return nil, nil, err
		}
		return keys, ent, nil
	}
}

func (d *ShardKindClient) GetOne(ctx context.Context, q *ShardQuery) (*datastore.Key, *Shard, error) {
	keys, ents, err := d.GetAll(ctx, q.Limit(1))
	if err != nil {
		return nil, nil, err
	}
	if len(keys) == 0 {
		return nil, nil, nil
	}
	return keys[0], &(ents[0]), nil
}

func (d *ShardKindClient) MustGetAll(ctx context.Context, q *ShardQuery) ([]*datastore.Key, []Shard) {
	keys, ents, err := d.GetAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents
}

func (d *ShardKindClient) Count(ctx context.Context, q *ShardQuery) (int, error) {
	return d.client.Count(ctx, q.query)
}

func (d *ShardKindClient) MustCount(ctx context.Context, q *ShardQuery) int {
	c, err := d.Count(ctx, q)
	xerrors.MustNil(err)
	return c
}

func (d *ShardKindClient) Run(ctx context.Context, q *ShardQuery) (*ShardIterator, error) {
	iter, err := d.client.Run(ctx, q.query)
	if err != nil {
		return nil, err
	}
	return &ShardIterator{
		ctx:     ctx,
		iter:    iter,
		viaKeys: q.viaKeys,
		client:  d,
	}, err
}

func (d *ShardKindClient) MustRun(ctx context.Context, q *ShardQuery) *ShardIterator {
	iter, err := d.Run(ctx, q)
	xerrors.MustNil(err)
	return iter
}

func (d *ShardKindClient) RunAll(ctx context.Context, q *ShardQuery) ([]datastore.Key, []Shard, string, error) {
	iter, err := d.Run(ctx, q)
	if err != nil {
		return nil, nil, "", err
	}
	var keys []datastore.Key
	var ents []Shard
	for {
		key, ent, err := iter.Next()
		if err != nil {
			return nil, nil, "", err
		}
		if ent == nil {
			cursor, err := iter.iter.Cursor()
			if err != nil {
				return nil, nil, "", err
			}
			return keys, ents, cursor.String(), nil
		}
		keys = append(keys, *key)
		ents = append(ents, *ent)
	}
}

func (d *ShardKindClient) MustRunAll(ctx context.Context, q *ShardQuery) ([]datastore.Key, []Shard, string) {
	keys, ents, next, err := d.RunAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents, next
}

type ShardIterator struct {
	ctx     context.Context
	iter    *datastore.Iterator
	viaKeys bool
	client  *ShardKindClient
}

func (iter *ShardIterator) Cursor() (datastore.Cursor, error) {
	return iter.iter.Cursor()
}

func (iter *ShardIterator) MustCursor() datastore.Cursor {
	c, err := iter.iter.Cursor()
	xerrors.MustNil(err)
	return c
}

func (iter *ShardIterator) Next() (*datastore.Key, *Shard, error) {
	if iter.viaKeys {
		key, err := iter.iter.Next(nil)
		if err != nil {
			if err == iterator.Done {
				return nil, nil, nil
			}
			return nil, nil, err
		}
		_, ent, err := iter.client.Get(iter.ctx, key)
		if err != nil {
			return nil, nil, err
		}
		return key, ent, nil
	}
	var ent Shard
	key, err := iter.iter.Next(&ent)
	if err != nil {
		if err == iterator.Done {
			return nil, nil, nil
		}
		return nil, nil, err
	}
	return key, &ent, nil
}

func (iter *ShardIterator) MustNext() (*datastore.Key, *Shard) {
	key, ent, err := iter.Next()
	xerrors.MustNil(err)
	return key, ent
}
