// Code generated by "ent -type=Auth"; DO NOT EDIT

package auth

import (
	"context"
	"fmt"
	"github.com/speedland/go/ent"
	helper "github.com/speedland/go/gae/datastore"
	"github.com/speedland/go/gae/memcache"
	"github.com/speedland/go/keyvalue"
	"github.com/speedland/go/lazy"
	"github.com/speedland/go/x/xerrors"
	"github.com/speedland/go/x/xlog"
	"github.com/speedland/go/x/xtime"
	"google.golang.org/appengine"
	"google.golang.org/appengine/datastore"
)

func (a *Auth) NewKey(ctx context.Context) *datastore.Key {
	return helper.NewKey(ctx, "Auth", a.ID)
}

// UpdateByForm updates the fields by form values. All values should be validated
// before calling this function.
func (a *Auth) UpdateByForm(form *keyvalue.GetProxy) {
}

// NewAuth returns a new *Auth with default field values.
func NewAuth() *Auth {
	a := &Auth{}
	return a
}

type AuthKind struct {
	useDefaultIfNil           bool
	noCache                   bool
	noSearchIndexing          bool
	ignoreSearchIndexingError bool
	noTimestampUpdate         bool
	enforceNamespace          bool
	namespace                 string
}

type AuthKindReplacer interface {
	Replace(*Auth, *Auth) *Auth
}

type AuthKindReplacerFunc func(*Auth, *Auth) *Auth

func (f AuthKindReplacerFunc) Replace(ent1 *Auth, ent2 *Auth) *Auth {
	return f(ent1, ent2)
}

// DefaultAuthKind is a default value of *AuthKind
var DefaultAuthKind = &AuthKind{}

// AuthKindLoggerKey is a logger key name for the ent
const AuthKindLoggerKey = "ent.auth"

// AuthQueryLoggerKey is a logger key name for the ent
const AuthQueryLoggerKey = "ent.query.auth"

// EnforceNamespace enforces namespace for Get/Put/Delete or not.
func (k *AuthKind) EnforceNamespace(ns string, b bool) *AuthKind {
	k.enforceNamespace = b
	k.namespace = ns
	return k
}

func (k *AuthKind) UseDefaultIfNil(b bool) *AuthKind {
	k.useDefaultIfNil = b
	return k
}

// Get gets the kind entity from datastore
func (k *AuthKind) Get(ctx context.Context, key interface{}) (*datastore.Key, *Auth, error) {
	keys, ents, err := k.GetMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

// MustGet is like Get but returns only values and panic if error happens.
func (k *AuthKind) MustGet(ctx context.Context, key interface{}) *Auth {
	_, v, err := k.Get(ctx, key)
	if err != nil {
		panic(err)
	}
	return v
}

// GetMulti do Get with multiple keys. keys must be []string, []*datastore.Key, or []interface{}
func (k *AuthKind) GetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*Auth, error) {
	ctx, logger := xlog.WithContextAndKey(ctx, "", AuthKindLoggerKey)
	var err error
	var dsKeys []*datastore.Key
	var memKeys []string
	var ents []*Auth
	if k.enforceNamespace {
		ctx, err = appengine.Namespace(ctx, k.namespace)
		if err != nil {
			return nil, nil, xerrors.Wrap(err, "cannot enforce namespace")
		}
	}
	dsKeys, err = k.normMultiKeys(ctx, keys)
	if err != nil {
		return nil, nil, xerrors.Wrap(err, "cannot normalize keys")
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil, nil
	}
	ents = make([]*Auth, size, size)
	// Memcache access
	if !k.noCache {
		logger.Debugf("Trying to get entities from memcache...")
		memKeys = make([]string, size, size)
		for i := range dsKeys {
			memKeys[i] = ent.GetMemcacheKey(dsKeys[i])
		}
		err = memcache.GetMulti(ctx, memKeys, ents)
		if err == nil {
			// Hit caches on all keys!!
			return dsKeys, ents, nil
		}
		logger.Debug(func(p *xlog.Printer) {
			p.Println("Auth#GetMulti [Memcache]")
			for i := 0; i < size; i++ {
				s := fmt.Sprintf("%v", ents[i])
				if len(s) > 20 {
					p.Printf("\t%s - %s...\n", memKeys[i], s[:20])
				} else {
					p.Printf("\t%s - %s\n", memKeys[i], s)
				}
				if i >= 20 {
					p.Printf("\t...(and %d ents)\n", size-i)
					break
				}
			}
		})
	}

	key2Idx := make(map[*datastore.Key]int)
	cacheMissingKeys := make([]*datastore.Key, 0)
	for i := range ents {
		if ents[i] == nil {
			key2Idx[dsKeys[i]] = i
			cacheMissingKeys = append(cacheMissingKeys, dsKeys[i])
		}
	}
	cacheMissingSize := len(cacheMissingKeys)

	// Datastore access
	cacheMissingEnts := make([]*Auth, cacheMissingSize, cacheMissingSize)
	err = helper.GetMulti(ctx, cacheMissingKeys, cacheMissingEnts)
	if helper.IsDatastoreError(err) {
		// we return nil even some ents hits the cache.
		return nil, nil, xerrors.Wrap(err, "datastore error")
	}

	if k.useDefaultIfNil {
		for i := 0; i < cacheMissingSize; i++ {
			if cacheMissingEnts[i] == nil {
				cacheMissingEnts[i] = NewAuth()
				cacheMissingEnts[i].ID = cacheMissingKeys[i].StringID() // TODO: Support non-string key as ID
			}
		}
	}

	// merge cacheMissingEnts with ents.
	for i := range cacheMissingKeys {
		entIdx := key2Idx[cacheMissingKeys[i]]
		ents[entIdx] = cacheMissingEnts[i]
	}

	// create a cache
	if !k.noCache {
		cacheEnts := make([]*Auth, 0)
		cacheKeys := make([]string, 0)
		for i := range ents {
			if ents[i] != nil {
				cacheEnts = append(cacheEnts, ents[i])
				cacheKeys = append(cacheKeys, memKeys[i])
			}
		}
		if len(cacheEnts) > 0 {
			if err := memcache.SetMulti(ctx, cacheKeys, cacheEnts); err != nil {
				logger.Warnf("Failed to create Auth) caches: %v", err)
			}
		}
	}

	logger.Debug(func(p *xlog.Printer) {
		p.Printf(
			"Auth#GetMulti [Datastore] (UseDefault: %t, NoCache: %t)\n",
			k.useDefaultIfNil, k.noCache,
		)
		for i := 0; i < size; i++ {
			s := fmt.Sprintf("%v", ents[i])
			if len(s) > 20 {
				p.Printf("\t%s - %s...\n", dsKeys[i], s[:20])
			} else {
				p.Printf("\t%s - %s\n", dsKeys[i], s)
			}
			if i >= 20 {
				p.Printf("\t...(and %d ents)\n", size-i)
				break
			}
		}
	})
	return dsKeys, ents, nil
}

// MustGetMulti is like GetMulti but returns only values and panic if error happens.
func (k *AuthKind) MustGetMulti(ctx context.Context, keys interface{}) []*Auth {
	_, v, err := k.GetMulti(ctx, keys)
	if err != nil {
		panic(err)
	}
	return v
}

// Put puts the entity to datastore.
func (k *AuthKind) Put(ctx context.Context, ent *Auth) (*datastore.Key, error) {
	keys, err := k.PutMulti(ctx, []*Auth{
		ent,
	})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

// MustPut is like Put and panic if an error occurrs.
func (k *AuthKind) MustPut(ctx context.Context, ent *Auth) *datastore.Key {
	keys, err := k.Put(ctx, ent)
	if err != nil {
		panic(err)
	}
	return keys
}

// PutMulti do Put with multiple keys
func (k *AuthKind) PutMulti(ctx context.Context, ents []*Auth) ([]*datastore.Key, error) {
	ctx, logger := xlog.WithContextAndKey(ctx, "", AuthKindLoggerKey)
	var err error
	var size = len(ents)
	var dsKeys []*datastore.Key
	if size == 0 {
		return nil, nil
	}
	if size >= ent.MaxEntsPerPutDelete {
		return nil, ent.ErrTooManyEnts
	}
	if k.enforceNamespace {
		ctx, err = appengine.Namespace(ctx, k.namespace)
		if err != nil {
			return nil, xerrors.Wrap(err, "cannot enforce namespace")
		}
	}
	dsKeys = make([]*datastore.Key, size, size)
	for i := range ents {
		if e, ok := interface{}(ents[i]).(ent.BeforeSave); ok {
			if err := e.BeforeSave(ctx); err != nil {
				return nil, err
			}
		}
		dsKeys[i] = ents[i].NewKey(ctx)
	}

	if !k.noTimestampUpdate {
		for i := range ents {
			ents[i].UpdatedAt = xtime.Now()
		}
	}

	_, err = helper.PutMulti(ctx, dsKeys, ents)
	if helper.IsDatastoreError(err) {
		return nil, xerrors.Wrap(err, "datastore error")
	}

	if !k.noCache {
		memKeys := make([]string, size, size)
		for i := range memKeys {
			memKeys[i] = ent.GetMemcacheKey(dsKeys[i])
		}
		err := memcache.DeleteMulti(ctx, memKeys)
		if memcache.IsMemcacheError(err) {
			logger.Warnf("Failed to invalidate memcache keys: %v", err)
		}
	}

	logger.Debug(func(p *xlog.Printer) {
		p.Printf(
			"Auth#PutMulti [Datastore] (NoCache: %t)\n",
			k.noCache,
		)
		for i := 0; i < size; i++ {
			s := fmt.Sprintf("%v", ents[i])
			if len(s) > 20 {
				p.Printf("\t%s - %s...\n", dsKeys[i], s[:20])
			} else {
				p.Printf("\t%s - %s\n", dsKeys[i], s)
			}
			if i >= 20 {
				p.Printf("\t...(and %d ents)\n", size-i)
				break
			}
		}
	})

	return dsKeys, nil
}

// MustPutMulti is like PutMulti but panic if an error occurs
func (k *AuthKind) MustPutMulti(ctx context.Context, ents []*Auth) []*datastore.Key {
	keys, err := k.PutMulti(ctx, ents)
	if err != nil {
		panic(err)
	}
	return keys
}

func (k *AuthKind) Replace(ctx context.Context, ent *Auth, replacer AuthKindReplacer) (*datastore.Key, *Auth, error) {
	keys, ents, err := k.ReplaceMulti(ctx, []*Auth{
		ent,
	}, replacer)
	if err != nil {
		return nil, ents[0], err
	}
	return keys[0], ents[0], err
}

func (k *AuthKind) MustReplace(ctx context.Context, ent *Auth, replacer AuthKindReplacer) (*datastore.Key, *Auth) {
	key, ent, err := k.Replace(ctx, ent, replacer)
	if err != nil {
		panic(err)
	}
	return key, ent
}

func (k *AuthKind) ReplaceMulti(ctx context.Context, ents []*Auth, replacer AuthKindReplacer) ([]*datastore.Key, []*Auth, error) {
	var size = len(ents)
	var dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return dsKeys, ents, nil
	}
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
	}
	_, existing, err := k.GetMulti(ctx, dsKeys)
	if err != nil {
		return nil, ents, err
	}
	for i, exist := range existing {
		if exist != nil {
			ents[i] = replacer.Replace(exist, ents[i])
		}
	}
	_, err = k.PutMulti(ctx, ents)
	return dsKeys, ents, err
}

func (k *AuthKind) MustReplaceMulti(ctx context.Context, ents []*Auth, replacer AuthKindReplacer) ([]*datastore.Key, []*Auth) {
	keys, ents, err := k.ReplaceMulti(ctx, ents, replacer)
	if err != nil {
		panic(err)
	}
	return keys, ents
}

// Delete deletes the entity from datastore
func (k *AuthKind) Delete(ctx context.Context, key interface{}) (*datastore.Key, error) {
	keys, err := k.DeleteMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

// MustDelete is like Delete but panic if an error occurs
func (k *AuthKind) MustDelete(ctx context.Context, key interface{}) *datastore.Key {
	_key, err := k.Delete(ctx, key)
	if err != nil {
		panic(err)
	}
	return _key
}

// DeleteMulti do Delete with multiple keys
func (k *AuthKind) DeleteMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, error) {
	ctx, logger := xlog.WithContextAndKey(ctx, "", AuthKindLoggerKey)
	var err error
	var dsKeys []*datastore.Key
	if k.enforceNamespace {
		ctx, err = appengine.Namespace(ctx, k.namespace)
		if err != nil {
			return nil, xerrors.Wrap(err, "cannot enforce namespace")
		}
	}
	dsKeys, err = k.normMultiKeys(ctx, keys)
	if err != nil {
		return nil, err
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil
	}
	if size >= ent.MaxEntsPerPutDelete {
		return nil, ent.ErrTooManyEnts
	}

	// Datastore access
	err = helper.DeleteMulti(ctx, dsKeys)
	if helper.IsDatastoreError(err) {
		// we return nil even some ents hits the cache.
		return nil, xerrors.Wrap(err, "datastore error")
	}

	if !k.noCache {
		memKeys := make([]string, size, size)
		for i := range memKeys {
			memKeys[i] = ent.GetMemcacheKey(dsKeys[i])
		}
		err = memcache.DeleteMulti(ctx, memKeys)
		if memcache.IsMemcacheError(err) {
			logger.Warnf("Failed to invalidate memcache keys: %v", err)
		}
	}

	logger.Debug(func(p *xlog.Printer) {
		p.Printf(
			"Auth#DeleteMulti [Datastore] (NoCache: %t)\n",
			k.noCache,
		)
		for i := 0; i < size; i++ {
			p.Printf("\t%s\n", dsKeys[i])
			if i >= 20 {
				p.Printf("\t...(and %d ents)\n", size-i)
				break
			}
		}
	})
	return dsKeys, nil
}

// MustDeleteMulti is like DeleteMulti but panic if an error occurs
func (k *AuthKind) MustDeleteMulti(ctx context.Context, keys interface{}) []*datastore.Key {
	_keys, err := k.DeleteMulti(ctx, keys)
	if err != nil {
		panic(err)
	}
	return _keys
}

func (k *AuthKind) normMultiKeys(ctx context.Context, keys interface{}) ([]*datastore.Key, error) {
	var dsKeys []*datastore.Key
	switch t := keys.(type) {
	case []string:
		tmp := keys.([]string)
		dsKeys = make([]*datastore.Key, len(tmp))
		for i, s := range tmp {
			dsKeys[i] = helper.NewKey(ctx, "Auth", s)
		}
	case []interface{}:
		tmp := keys.([]interface{})
		dsKeys = make([]*datastore.Key, len(tmp))
		for i, s := range tmp {
			dsKeys[i] = helper.NewKey(ctx, "Auth", s)
		}
	case []*datastore.Key:
		dsKeys = keys.([]*datastore.Key)
	default:
		return nil, fmt.Errorf("unsupported keys type: %s", t)
	}
	return dsKeys, nil
}

// AuthQuery helps to build and execute a query
type AuthQuery struct {
	q *helper.Query
}

func NewAuthQuery() *AuthQuery {
	return &AuthQuery{
		q: helper.NewQuery("Auth", AuthQueryLoggerKey),
	}
}

// Ancestor sets the ancestor filter
func (q *AuthQuery) Ancestor(a lazy.Value) *AuthQuery {
	q.q = q.q.Ancestor(a)
	return q
}

// Eq sets the "=" filter on the name field.
func (q *AuthQuery) Eq(name string, value lazy.Value) *AuthQuery {
	q.q = q.q.Eq(name, value)
	return q
}

// Lt sets the "<" filter on the "name" field.
func (q *AuthQuery) Lt(name string, value lazy.Value) *AuthQuery {
	q.q = q.q.Lt(name, value)
	return q
}

// Le sets the "<=" filter on the "name" field.
func (q *AuthQuery) Le(name string, value lazy.Value) *AuthQuery {
	q.q = q.q.Le(name, value)
	return q
}

// Gt sets the ">" filter on the "name" field.
func (q *AuthQuery) Gt(name string, value lazy.Value) *AuthQuery {
	q.q = q.q.Gt(name, value)
	return q
}

// Ge sets the ">=" filter on the "name" field.
func (q *AuthQuery) Ge(name string, value lazy.Value) *AuthQuery {
	q.q = q.q.Ge(name, value)
	return q
}

// Ne sets the "!=" filter on the "name" field.
func (q *AuthQuery) Ne(name string, value lazy.Value) *AuthQuery {
	q.q = q.q.Ne(name, value)
	return q
}

// Asc specifies ascending order on the given filed.
func (q *AuthQuery) Asc(name string) *AuthQuery {
	q.q = q.q.Asc(name)
	return q
}

// Desc specifies descending order on the given filed.
func (q *AuthQuery) Desc(name string) *AuthQuery {
	q.q = q.q.Desc(name)
	return q
}

// Limit specifies the numbe of limit returend by this query.
func (q *AuthQuery) Limit(n lazy.Value) *AuthQuery {
	q.q = q.q.Limit(n)
	return q
}

// Limit specifies the numbe of limit returend by this query.
func (q *AuthQuery) Start(value lazy.Value) *AuthQuery {
	q.q = q.q.Start(value)
	return q
}

// Limit specifies the numbe of limit returend by this query.
func (q *AuthQuery) End(value lazy.Value) *AuthQuery {
	q.q = q.q.End(value)
	return q
}

// GetAll returns all key and value of the query.
func (q *AuthQuery) GetAll(ctx context.Context) ([]*datastore.Key, []*Auth, error) {
	var v []*Auth
	keys, err := q.q.GetAll(ctx, &v)
	if err != nil {
		return nil, nil, err
	}
	return keys, v, err
}

// MustGetAll is like GetAll but panic if an error occurrs.
func (q *AuthQuery) MustGetAll(ctx context.Context) ([]*datastore.Key, []*Auth) {
	keys, values, err := q.GetAll(ctx)
	if err != nil {
		panic(err)
	}
	return keys, values
}

// GetAllValues is like GetAll but returns only values
func (q *AuthQuery) GetAllValues(ctx context.Context) ([]*Auth, error) {
	var v []*Auth
	_, err := q.q.GetAll(ctx, &v)
	if err != nil {
		return nil, err
	}
	return v, err
}

// MustGetAllValues is like GetAllValues but panic if an error occurrs
func (q *AuthQuery) MustGetAllValues(ctx context.Context) []*Auth {
	var v []*Auth
	_, err := q.q.GetAll(ctx, &v)
	if err != nil {
		panic(err)
	}
	return v
}

// Count returns the count of entities
func (q *AuthQuery) Count(ctx context.Context) (int, error) {
	return q.q.Count(ctx)
}

// MustCount returns the count of entities
func (q *AuthQuery) MustCount(ctx context.Context) int {
	c, err := q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return c
}

type AuthPagination struct {
	Start string           `json:"start"`
	End   string           `json:"end"`
	Count int              `json:"count,omitempty"`
	Data  []*Auth          `json:"data"`
	Keys  []*datastore.Key `json:"-"`
}

// Run returns the a result as *AuthPagination object
func (q *AuthQuery) Run(ctx context.Context) (*AuthPagination, error) {
	iter, err := q.q.Run(ctx)
	if err != nil {
		return nil, err
	}
	pagination := &AuthPagination{}
	keys := []*datastore.Key{}
	data := []*Auth{}
	start, err := iter.Cursor()
	if err != nil {
		return nil, fmt.Errorf("couldn't get the start cursor: %v", err)
	}
	pagination.Start = start.String()
	for {
		var ent Auth
		key, err := iter.Next(&ent)
		if err == datastore.Done {
			end, err := iter.Cursor()
			if err != nil {
				return nil, fmt.Errorf("couldn't get the end cursor: %v", err)
			}
			pagination.Keys = keys
			pagination.Data = data
			pagination.End = end.String()
			return pagination, nil
		}
		if err != nil {
			return nil, err
		}
		keys = append(keys, key)
		data = append(data, &ent)
	}
}

// MustRun is like Run but panic if an error occurrs
func (q *AuthQuery) MustRun(ctx context.Context) *AuthPagination {
	p, err := q.Run(ctx)
	if err != nil {
		panic(err)
	}
	return p
}

// DeleteMatched deletes the all ents that match with the query.
// This func modify Limit/StartKey condition in the query so that you should restore it
// if you want to reuse the query.
func (k *AuthKind) DeleteMatched(ctx context.Context, q *AuthQuery) (int, error) {
	var numDeletes int
	var startKey string
	q.Limit(lazy.New(ent.MaxEntsPerPutDelete - 5))
	// TODO: canceling the context
	for {
		if startKey != "" {
			q.Start(lazy.New(startKey))
		}
		page := q.MustRun(ctx)
		if len(page.Keys) == 0 {
			return numDeletes, nil
		}
		_, err := k.DeleteMulti(ctx, page.Keys)
		if err != nil {
			return numDeletes, fmt.Errorf("couldn't delete matched ents: %v", err)
		} else {
			numDeletes += len(page.Keys)
		}
		startKey = page.End
	}
}
