// Code generated by github.com/yssk22/go/generator DO NOT EDIT.
//
package asynctask

import (
	"context"
	"time"

	"cloud.google.com/go/datastore"
	ds "github.com/yssk22/go/gcp/datastore"
	"github.com/yssk22/go/x/xerrors"
	"github.com/yssk22/go/x/xtime"
	"google.golang.org/api/iterator"
)

func (s *AsyncTask) NewKey(ctx context.Context) *datastore.Key {
	key := ds.NewKey("AsyncTask", s.ID)
	key.Namespace = ""
	return key
}

type AsyncTaskReplacer interface {
	Replace(*AsyncTask, *AsyncTask) *AsyncTask
}

type AsyncTaskReplacerFunc func(*AsyncTask, *AsyncTask) *AsyncTask

func (f AsyncTaskReplacerFunc) Replace(old *AsyncTask, new *AsyncTask) *AsyncTask {
	return f(old, new)
}

type AsyncTaskKindClient struct {
	client *ds.Client
}

func NewAsyncTaskKindClient(client *ds.Client) *AsyncTaskKindClient {
	return &AsyncTaskKindClient{
		client: client,
	}
}

func (d *AsyncTaskKindClient) Get(ctx context.Context, key interface{}) (*datastore.Key, *AsyncTask, error) {
	keys, ents, err := d.GetMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

func (d *AsyncTaskKindClient) MustGet(ctx context.Context, key interface{}) (*datastore.Key, *AsyncTask) {
	k, v, e := d.Get(ctx, key)
	xerrors.MustNil(e)
	return k, v
}

func (d *AsyncTaskKindClient) GetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*AsyncTask, error) {
	var err error
	var dsKeys []*datastore.Key
	var ents []*AsyncTask
	if dsKeys, err = ds.NormalizeKeys(keys, "AsyncTask", ""); err != nil {
		return nil, nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil, nil
	}
	ents = make([]*AsyncTask, size, size)
	if err = d.client.GetMulti(ctx, dsKeys, ents); err != nil {
		return nil, nil, err
	}
	return dsKeys, ents, nil
}

func (d *AsyncTaskKindClient) MustGetMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, []*AsyncTask) {
	k, v, e := d.GetMulti(ctx, keys)
	xerrors.MustNil(e)
	return k, v
}

func (d *AsyncTaskKindClient) Put(ctx context.Context, ent *AsyncTask) (*datastore.Key, error) {
	keys, err := d.PutMulti(ctx, []*AsyncTask{ent})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *AsyncTaskKindClient) MustPut(ctx context.Context, ent *AsyncTask) *datastore.Key {
	k, e := d.Put(ctx, ent)
	xerrors.MustNil(e)
	return k
}

func (d *AsyncTaskKindClient) PutMulti(ctx context.Context, ents []*AsyncTask) ([]*datastore.Key, error) {
	var err error
	var size = len(ents)
	var dsKeys []*datastore.Key
	dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return nil, nil
	}
	_, hasBeforeSave := interface{}(ents[0]).(ds.BeforeSave)
	_, hasAfterSave := interface{}(ents[0]).(ds.AfterSave)

	if hasBeforeSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.BeforeSave).BeforeSave(ctx); err != nil {
				return nil, err
			}
		}
	}

	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
		ents[i].UpdatedAt = xtime.Now()
	}
	if dsKeys, err = d.client.PutMulti(ctx, dsKeys, ents); err != nil {
		return nil, err
	}

	if hasAfterSave {
		for i := range ents {
			if err := interface{}(ents[i]).(ds.AfterSave).AfterSave(ctx); err != nil {
				return nil, err
			}
		}
	}
	return dsKeys, nil
}

func (d *AsyncTaskKindClient) MustPutMulti(ctx context.Context, ents []*AsyncTask) []*datastore.Key {
	keys, err := d.PutMulti(ctx, ents)
	xerrors.MustNil(err)
	return keys
}

func (d *AsyncTaskKindClient) Delete(ctx context.Context, key interface{}) (*datastore.Key, error) {
	keys, err := d.DeleteMulti(ctx, []interface{}{key})
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *AsyncTaskKindClient) MustDelete(ctx context.Context, key interface{}) *datastore.Key {
	k, e := d.Delete(ctx, key)
	xerrors.MustNil(e)
	return k
}

func (d *AsyncTaskKindClient) DeleteMulti(ctx context.Context, keys interface{}) ([]*datastore.Key, error) {
	var err error
	var dsKeys []*datastore.Key
	if dsKeys, err = ds.NormalizeKeys(keys, "AsyncTask", ""); err != nil {
		return nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil
	}
	if err = d.client.DeleteMulti(ctx, dsKeys); err != nil {
		return nil, xerrors.Wrap(err, "datastore error")
	}
	return dsKeys, nil
}

func (d *AsyncTaskKindClient) MustDeleteMulti(ctx context.Context, keys interface{}) []*datastore.Key {
	k, e := d.DeleteMulti(ctx, keys)
	xerrors.MustNil(e)
	return k
}

func (d *AsyncTaskKindClient) DeleteMatched(ctx context.Context, q *AsyncTaskQuery) ([]*datastore.Key, error) {
	keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
	if err != nil {
		return nil, err
	}
	_, err = d.DeleteMulti(ctx, keys)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

func (d *AsyncTaskKindClient) MustDeleteMatched(ctx context.Context, q *AsyncTaskQuery) []*datastore.Key {
	keys, err := d.DeleteMatched(ctx, q)
	xerrors.MustNil(err)
	return keys
}

func (d *AsyncTaskKindClient) Replace(ctx context.Context, ent *AsyncTask, replacer AsyncTaskReplacer) (*datastore.Key, *AsyncTask, error) {
	keys, ents, err := d.ReplaceMulti(ctx, []*AsyncTask{ent}, replacer)
	if err != nil {
		return nil, ents[0], err
	}
	return keys[0], ents[0], err
}

func (d *AsyncTaskKindClient) MustReplace(ctx context.Context, ent *AsyncTask, replacer AsyncTaskReplacer) (*datastore.Key, *AsyncTask) {
	k, v, e := d.Replace(ctx, ent, replacer)
	xerrors.MustNil(e)
	return k, v
}

func (d *AsyncTaskKindClient) ReplaceMulti(ctx context.Context, ents []*AsyncTask, replacer AsyncTaskReplacer) ([]*datastore.Key, []*AsyncTask, error) {
	var size = len(ents)
	var dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return dsKeys, ents, nil
	}
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
	}
	_, existing, err := d.GetMulti(ctx, dsKeys)
	if err != nil {
		return nil, ents, err
	}
	for i, exist := range existing {
		if exist != nil {
			ents[i] = replacer.Replace(exist, ents[i])
		}
	}
	dsKeys, err = d.PutMulti(ctx, ents)
	return dsKeys, ents, err
}

func (d *AsyncTaskKindClient) MustReplaceMulti(ctx context.Context, ents []*AsyncTask, replacer AsyncTaskReplacer) ([]*datastore.Key, []*AsyncTask) {
	k, v, e := d.ReplaceMulti(ctx, ents, replacer)
	xerrors.MustNil(e)
	return k, v
}

type AsyncTaskQuery struct {
	query   *ds.Query
	viaKeys bool
}

func NewAsyncTaskQuery() *AsyncTaskQuery {
	return &AsyncTaskQuery{
		query:   ds.NewQuery("AsyncTask").Namespace(""),
		viaKeys: false,
	}
}

func (d *AsyncTaskQuery) EqID(v string) *AsyncTaskQuery {
	d.query = d.query.Eq("ID", v)
	return d
}

func (d *AsyncTaskQuery) EqConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Eq("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) EqStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Eq("Status", v)
	return d
}

func (d *AsyncTaskQuery) EqStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Eq("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) EqFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Eq("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) EqUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Eq("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) LtID(v string) *AsyncTaskQuery {
	d.query = d.query.Lt("ID", v)
	return d
}

func (d *AsyncTaskQuery) LtConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Lt("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) LtStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Lt("Status", v)
	return d
}

func (d *AsyncTaskQuery) LtStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Lt("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) LtFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Lt("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) LtUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Lt("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) LeID(v string) *AsyncTaskQuery {
	d.query = d.query.Le("ID", v)
	return d
}

func (d *AsyncTaskQuery) LeConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Le("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) LeStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Le("Status", v)
	return d
}

func (d *AsyncTaskQuery) LeStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Le("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) LeFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Le("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) LeUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Le("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) GtID(v string) *AsyncTaskQuery {
	d.query = d.query.Gt("ID", v)
	return d
}

func (d *AsyncTaskQuery) GtConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Gt("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) GtStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Gt("Status", v)
	return d
}

func (d *AsyncTaskQuery) GtStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Gt("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) GtFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Gt("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) GtUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Gt("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) GeID(v string) *AsyncTaskQuery {
	d.query = d.query.Ge("ID", v)
	return d
}

func (d *AsyncTaskQuery) GeConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Ge("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) GeStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Ge("Status", v)
	return d
}

func (d *AsyncTaskQuery) GeStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ge("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) GeFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ge("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) GeUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ge("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) NeID(v string) *AsyncTaskQuery {
	d.query = d.query.Ne("ID", v)
	return d
}

func (d *AsyncTaskQuery) NeConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Ne("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) NeStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Ne("Status", v)
	return d
}

func (d *AsyncTaskQuery) NeStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ne("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) NeFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ne("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) NeUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ne("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) AscID() *AsyncTaskQuery {
	d.query = d.query.Asc("ID")
	return d
}

func (d *AsyncTaskQuery) AscConfigKey() *AsyncTaskQuery {
	d.query = d.query.Asc("ConfigKey")
	return d
}

func (d *AsyncTaskQuery) AscStatus() *AsyncTaskQuery {
	d.query = d.query.Asc("Status")
	return d
}

func (d *AsyncTaskQuery) AscStartAt() *AsyncTaskQuery {
	d.query = d.query.Asc("StartAt")
	return d
}

func (d *AsyncTaskQuery) AscFinishAt() *AsyncTaskQuery {
	d.query = d.query.Asc("FinishAt")
	return d
}

func (d *AsyncTaskQuery) AscUpdatedAt() *AsyncTaskQuery {
	d.query = d.query.Asc("UpdatedAt")
	return d
}

func (d *AsyncTaskQuery) DescID() *AsyncTaskQuery {
	d.query = d.query.Desc("ID")
	return d
}

func (d *AsyncTaskQuery) DescConfigKey() *AsyncTaskQuery {
	d.query = d.query.Desc("ConfigKey")
	return d
}

func (d *AsyncTaskQuery) DescStatus() *AsyncTaskQuery {
	d.query = d.query.Desc("Status")
	return d
}

func (d *AsyncTaskQuery) DescStartAt() *AsyncTaskQuery {
	d.query = d.query.Desc("StartAt")
	return d
}

func (d *AsyncTaskQuery) DescFinishAt() *AsyncTaskQuery {
	d.query = d.query.Desc("FinishAt")
	return d
}

func (d *AsyncTaskQuery) DescUpdatedAt() *AsyncTaskQuery {
	d.query = d.query.Desc("UpdatedAt")
	return d
}

func (q *AsyncTaskQuery) Start(s string) *AsyncTaskQuery {
	q.query = q.query.Start(s)
	return q
}

func (q *AsyncTaskQuery) End(s string) *AsyncTaskQuery {
	q.query = q.query.End(s)
	return q
}

func (q *AsyncTaskQuery) Limit(n int) *AsyncTaskQuery {
	q.query = q.query.Limit(n)
	return q
}

func (q *AsyncTaskQuery) ViaKeys() *AsyncTaskQuery {
	q.viaKeys = true
	return q
}

func (d *AsyncTaskKindClient) GetAll(ctx context.Context, q *AsyncTaskQuery) ([]*datastore.Key, []AsyncTask, error) {
	if q.viaKeys {
		keys, err := d.client.GetAll(ctx, q.query.KeysOnly(), nil)
		if err != nil {
			return nil, nil, err
		}
		ents := make([]*AsyncTask, len(keys))
		err = d.client.GetMulti(ctx, keys, ents)
		if err != nil {
			return nil, nil, err
		}
		result := make([]AsyncTask, 0)
		for _, e := range ents {
			if e != nil {
				result = append(result, *e)
			}
		}
		return keys, result, nil
	} else {
		var ent []AsyncTask
		keys, err := d.client.GetAll(ctx, q.query, &ent)
		if err != nil {
			return nil, nil, err
		}
		return keys, ent, nil
	}
}

func (d *AsyncTaskKindClient) GetOne(ctx context.Context, q *AsyncTaskQuery) (*datastore.Key, *AsyncTask, error) {
	keys, ents, err := d.GetAll(ctx, q.Limit(1))
	if err != nil {
		return nil, nil, err
	}
	if len(keys) == 0 {
		return nil, nil, nil
	}
	return keys[0], &(ents[0]), nil
}

func (d *AsyncTaskKindClient) MustGetAll(ctx context.Context, q *AsyncTaskQuery) ([]*datastore.Key, []AsyncTask) {
	keys, ents, err := d.GetAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents
}

func (d *AsyncTaskKindClient) Count(ctx context.Context, q *AsyncTaskQuery) (int, error) {
	return d.client.Count(ctx, q.query)
}

func (d *AsyncTaskKindClient) MustCount(ctx context.Context, q *AsyncTaskQuery) int {
	c, err := d.Count(ctx, q)
	xerrors.MustNil(err)
	return c
}

func (d *AsyncTaskKindClient) Run(ctx context.Context, q *AsyncTaskQuery) (*AsyncTaskIterator, error) {
	iter, err := d.client.Run(ctx, q.query)
	if err != nil {
		return nil, err
	}
	return &AsyncTaskIterator{
		ctx:     ctx,
		iter:    iter,
		viaKeys: q.viaKeys,
		client:  d,
	}, err
}

func (d *AsyncTaskKindClient) MustRun(ctx context.Context, q *AsyncTaskQuery) *AsyncTaskIterator {
	iter, err := d.Run(ctx, q)
	xerrors.MustNil(err)
	return iter
}

func (d *AsyncTaskKindClient) RunAll(ctx context.Context, q *AsyncTaskQuery) ([]datastore.Key, []AsyncTask, string, error) {
	iter, err := d.Run(ctx, q)
	if err != nil {
		return nil, nil, "", err
	}
	var keys []datastore.Key
	var ents []AsyncTask
	for {
		key, ent, err := iter.Next()
		if err != nil {
			return nil, nil, "", err
		}
		if ent == nil {
			cursor, err := iter.iter.Cursor()
			if err != nil {
				return nil, nil, "", err
			}
			return keys, ents, cursor.String(), nil
		}
		keys = append(keys, *key)
		ents = append(ents, *ent)
	}
}

func (d *AsyncTaskKindClient) MustRunAll(ctx context.Context, q *AsyncTaskQuery) ([]datastore.Key, []AsyncTask, string) {
	keys, ents, next, err := d.RunAll(ctx, q)
	xerrors.MustNil(err)
	return keys, ents, next
}

type AsyncTaskIterator struct {
	ctx     context.Context
	iter    *datastore.Iterator
	viaKeys bool
	client  *AsyncTaskKindClient
}

func (iter *AsyncTaskIterator) Cursor() (datastore.Cursor, error) {
	return iter.iter.Cursor()
}

func (iter *AsyncTaskIterator) MustCursor() datastore.Cursor {
	c, err := iter.iter.Cursor()
	xerrors.MustNil(err)
	return c
}

func (iter *AsyncTaskIterator) Next() (*datastore.Key, *AsyncTask, error) {
	if iter.viaKeys {
		key, err := iter.iter.Next(nil)
		if err != nil {
			if err == iterator.Done {
				return nil, nil, nil
			}
			return nil, nil, err
		}
		_, ent, err := iter.client.Get(iter.ctx, key)
		if err != nil {
			return nil, nil, err
		}
		return key, ent, nil
	}
	var ent AsyncTask
	key, err := iter.iter.Next(&ent)
	if err != nil {
		if err == iterator.Done {
			return nil, nil, nil
		}
		return nil, nil, err
	}
	return key, &ent, nil
}

func (iter *AsyncTaskIterator) MustNext() (*datastore.Key, *AsyncTask) {
	key, ent, err := iter.Next()
	xerrors.MustNil(err)
	return key, ent
}
