// Code generated by github.com/yssk22/go/generator DO NOT EDIT.
//
package asynctask

import (
	"encoding/json"
	"fmt"
)

var (
	_StatusValueToString = map[Status]string{
		StatusUnknown: "unknown",
		StatusReady:   "ready",
		StatusRunning: "running",
		StatusSuccess: "success",
		StatusFailure: "failure",
	}
	_StatusStringToValue = map[string]Status{
		"unknown": StatusUnknown,
		"ready":   StatusReady,
		"running": StatusRunning,
		"success": StatusSuccess,
		"failure": StatusFailure,
	}
)

func (e Status) String() string {
	if str, ok := _StatusValueToString[e]; ok {
		return str
	}
	return fmt.Sprintf("Status(%d)", e)
}

func (e Status) IsVaild() bool {
	_, ok := _StatusValueToString[e]
	return ok
}

func ParseStatus(s string) (Status, error) {
	if val, ok := _StatusStringToValue[s]; ok {
		return val, nil
	}
	return Status(-1), fmt.Errorf("invalid value %q for Status", s)
}

func ParseStatusOr(s string, or Status) Status {
	val, err := ParseStatus(s)
	if err != nil {
		return or
	}
	return val
}

func MustParseStatus(s string) Status {
	val, err := ParseStatus(s)
	if err != nil {
		panic(err)
	}
	return val
}

func (e Status) MarshalJSON() ([]byte, error) {
	var s string
	var ok bool
	if s, ok = _StatusValueToString[e]; !ok {
		s = fmt.Sprintf("Status(%d)", e)
	}
	return json.Marshal(s)
}

func (e *Status) UnmarshalJSON(b []byte) error {
	if b[0] != '"' || b[len(b)-1] != '"' {
		return fmt.Errorf("invalid JSON string")
	}
	newval, err := ParseStatus(string(b[1 : len(b)-1]))
	if err != nil {
		return err
	}
	*e = newval
	return nil
}

func (e *Status) Parse(s string) error {
	if val, ok := _StatusStringToValue[s]; ok {
		*e = val
		return nil
	}
	return fmt.Errorf("invalid value %q for Status", s)
}
