// Code generated by github.com/yssk22/go/generator DO NOT EDIT.
//
package asynctask

import (
	"context"
	ds "github.com/yssk22/go/gae/datastore"
	"github.com/yssk22/go/x/xerrors"
	"github.com/yssk22/go/x/xtime"
	"google.golang.org/appengine/datastore"
	"time"
)

func (s *AsyncTask) NewKey(ctx context.Context) *datastore.Key {
	return ds.NewKey(ctx, "AsyncTask", s.ID)
}

type AsyncTaskReplacer interface {
	Replace(*AsyncTask, *AsyncTask) *AsyncTask
}

type AsyncTaskReplacerFunc func(*AsyncTask, *AsyncTask) *AsyncTask

func (f AsyncTaskReplacerFunc) Replace(old *AsyncTask, new *AsyncTask) *AsyncTask {
	return f(old, new)
}

type AsyncTaskKind struct{}

func NewAsyncTaskKind() *AsyncTaskKind {
	return AAsyncTaskKindInstance
}

func (d *AsyncTaskKind) Get(ctx context.Context, key interface{}, options ...ds.CRUDOption) (*datastore.Key, *AsyncTask, error) {
	keys, ents, err := d.GetMulti(ctx, []interface{}{key}, options...)
	if err != nil {
		return nil, nil, err
	}
	return keys[0], ents[0], nil
}

func (d *AsyncTaskKind) MustGet(ctx context.Context, key interface{}, options ...ds.CRUDOption) (*datastore.Key, *AsyncTask) {
	k, v, e := d.Get(ctx, key, options...)
	xerrors.MustNil(e)
	return k, v
}

func (d *AsyncTaskKind) GetMulti(ctx context.Context, keys interface{}, options ...ds.CRUDOption) ([]*datastore.Key, []*AsyncTask, error) {
	var err error
	var dsKeys []*datastore.Key
	var ents []*AsyncTask
	if dsKeys, err = ds.NormalizeKeys(ctx, "AsyncTask", keys); err != nil {
		return nil, nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil, nil
	}
	ents = make([]*AsyncTask, size, size)
	if err = ds.GetMulti(ctx, dsKeys, ents, options...); err != nil {
		return nil, nil, err
	}
	return dsKeys, ents, nil
}

func (d *AsyncTaskKind) MustGetMulti(ctx context.Context, keys interface{}, options ...ds.CRUDOption) ([]*datastore.Key, []*AsyncTask) {
	k, v, e := d.GetMulti(ctx, keys, options...)
	xerrors.MustNil(e)
	return k, v
}

func (d *AsyncTaskKind) Put(ctx context.Context, ent *AsyncTask, options ...ds.CRUDOption) (*datastore.Key, error) {
	keys, err := d.PutMulti(ctx, []*AsyncTask{ent}, options...)
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *AsyncTaskKind) MustPut(ctx context.Context, ent *AsyncTask, options ...ds.CRUDOption) *datastore.Key {
	k, e := d.Put(ctx, ent, options...)
	xerrors.MustNil(e)
	return k
}

func (d *AsyncTaskKind) PutMulti(ctx context.Context, ents []*AsyncTask, options ...ds.CRUDOption) ([]*datastore.Key, error) {
	var err error
	var size = len(ents)
	var dsKeys []*datastore.Key
	dsKeys = make([]*datastore.Key, size, size)
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
		ents[i].UpdatedAt = xtime.Now()
	}
	if dsKeys, err = ds.PutMulti(ctx, dsKeys, ents); err != nil {
		return nil, err
	}
	return dsKeys, nil
}

func (d *AsyncTaskKind) MustPutMulti(ctx context.Context, ents []*AsyncTask, options ...ds.CRUDOption) []*datastore.Key {
	keys, err := d.PutMulti(ctx, ents, options...)
	xerrors.MustNil(err)
	return keys
}

func (d *AsyncTaskKind) Delete(ctx context.Context, key interface{}, options ...ds.CRUDOption) (*datastore.Key, error) {
	keys, err := d.DeleteMulti(ctx, []interface{}{key}, options...)
	if err != nil {
		return nil, err
	}
	return keys[0], nil
}

func (d *AsyncTaskKind) MustDelete(ctx context.Context, key interface{}, options ...ds.CRUDOption) *datastore.Key {
	k, e := d.Delete(ctx, key, options...)
	xerrors.MustNil(e)
	return k
}

func (d *AsyncTaskKind) DeleteMulti(ctx context.Context, keys interface{}, options ...ds.CRUDOption) ([]*datastore.Key, error) {
	var err error
	var dsKeys []*datastore.Key
	if dsKeys, err = ds.NormalizeKeys(ctx, "AsyncTask", keys); err != nil {
		return nil, xerrors.Wrap(err, "could not normalize keys: %v", keys)
	}
	size := len(dsKeys)
	if size == 0 {
		return nil, nil
	}
	if err = ds.DeleteMulti(ctx, dsKeys); err != nil {
		return nil, xerrors.Wrap(err, "datastore error")
	}
	return dsKeys, nil
}

func (d *AsyncTaskKind) MustDeleteMulti(ctx context.Context, keys interface{}, options ...ds.CRUDOption) []*datastore.Key {
	k, e := d.DeleteMulti(ctx, keys, options...)
	xerrors.MustNil(e)
	return k
}

func (d *AsyncTaskKind) DeleteMatched(ctx context.Context, q *AsyncTaskQuery, options ...ds.CRUDOption) ([]*datastore.Key, error) {
	keys, err := q.query.KeysOnly().GetAll(ctx, nil)
	if err != nil {
		return nil, err
	}
	_, err = d.DeleteMulti(ctx, keys, options...)
	if err != nil {
		return nil, err
	}
	return keys, nil
}

func (d *AsyncTaskKind) MustDeleteMatched(ctx context.Context, q *AsyncTaskQuery, options ...ds.CRUDOption) []*datastore.Key {
	keys, err := d.DeleteMatched(ctx, q, options...)
	xerrors.MustNil(err)
	return keys
}

func (d *AsyncTaskKind) Replace(ctx context.Context, ent *AsyncTask, replacer AsyncTaskReplacer, options ...ds.CRUDOption) (*datastore.Key, *AsyncTask, error) {
	keys, ents, err := d.ReplaceMulti(ctx, []*AsyncTask{ent}, replacer, options...)
	if err != nil {
		return nil, ents[0], err
	}
	return keys[0], ents[0], err
}

func (d *AsyncTaskKind) MustReplace(ctx context.Context, ent *AsyncTask, replacer AsyncTaskReplacer, options ...ds.CRUDOption) (*datastore.Key, *AsyncTask) {
	k, v, e := d.Replace(ctx, ent, replacer, options...)
	xerrors.MustNil(e)
	return k, v
}

func (d *AsyncTaskKind) ReplaceMulti(ctx context.Context, ents []*AsyncTask, replacer AsyncTaskReplacer, options ...ds.CRUDOption) ([]*datastore.Key, []*AsyncTask, error) {
	var size = len(ents)
	var dsKeys = make([]*datastore.Key, size, size)
	if size == 0 {
		return dsKeys, ents, nil
	}
	for i := range ents {
		dsKeys[i] = ents[i].NewKey(ctx)
	}
	_, existing, err := d.GetMulti(ctx, dsKeys)
	if err != nil {
		return nil, ents, err
	}
	for i, exist := range existing {
		if exist != nil {
			ents[i] = replacer.Replace(exist, ents[i])
		}
	}
	dsKeys, err = d.PutMulti(ctx, ents)
	return dsKeys, ents, err
}

func (d *AsyncTaskKind) MustReplaceMulti(ctx context.Context, ents []*AsyncTask, replacer AsyncTaskReplacer, options ...ds.CRUDOption) ([]*datastore.Key, []*AsyncTask) {
	k, v, e := d.ReplaceMulti(ctx, ents, replacer, options...)
	xerrors.MustNil(e)
	return k, v
}

type AsyncTaskQuery struct {
	query   *ds.Query
	viaKeys bool
}

func NewAsyncTaskQuery() *AsyncTaskQuery {
	return &AsyncTaskQuery{
		query:   ds.NewQuery("AsyncTask"),
		viaKeys: false,
	}
}

func (d *AsyncTaskQuery) EqID(v string) *AsyncTaskQuery {
	d.query = d.query.Eq("ID", v)
	return d
}

func (d *AsyncTaskQuery) EqConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Eq("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) EqStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Eq("Status", v)
	return d
}

func (d *AsyncTaskQuery) EqStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Eq("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) EqFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Eq("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) EqUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Eq("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) LtID(v string) *AsyncTaskQuery {
	d.query = d.query.Lt("ID", v)
	return d
}

func (d *AsyncTaskQuery) LtConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Lt("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) LtStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Lt("Status", v)
	return d
}

func (d *AsyncTaskQuery) LtStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Lt("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) LtFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Lt("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) LtUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Lt("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) LeID(v string) *AsyncTaskQuery {
	d.query = d.query.Le("ID", v)
	return d
}

func (d *AsyncTaskQuery) LeConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Le("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) LeStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Le("Status", v)
	return d
}

func (d *AsyncTaskQuery) LeStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Le("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) LeFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Le("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) LeUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Le("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) GtID(v string) *AsyncTaskQuery {
	d.query = d.query.Gt("ID", v)
	return d
}

func (d *AsyncTaskQuery) GtConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Gt("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) GtStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Gt("Status", v)
	return d
}

func (d *AsyncTaskQuery) GtStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Gt("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) GtFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Gt("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) GtUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Gt("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) GeID(v string) *AsyncTaskQuery {
	d.query = d.query.Ge("ID", v)
	return d
}

func (d *AsyncTaskQuery) GeConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Ge("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) GeStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Ge("Status", v)
	return d
}

func (d *AsyncTaskQuery) GeStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ge("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) GeFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ge("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) GeUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ge("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) NeID(v string) *AsyncTaskQuery {
	d.query = d.query.Ne("ID", v)
	return d
}

func (d *AsyncTaskQuery) NeConfigKey(v string) *AsyncTaskQuery {
	d.query = d.query.Ne("ConfigKey", v)
	return d
}

func (d *AsyncTaskQuery) NeStatus(v Status) *AsyncTaskQuery {
	d.query = d.query.Ne("Status", v)
	return d
}

func (d *AsyncTaskQuery) NeStartAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ne("StartAt", v)
	return d
}

func (d *AsyncTaskQuery) NeFinishAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ne("FinishAt", v)
	return d
}

func (d *AsyncTaskQuery) NeUpdatedAt(v time.Time) *AsyncTaskQuery {
	d.query = d.query.Ne("UpdatedAt", v)
	return d
}

func (d *AsyncTaskQuery) AscID() *AsyncTaskQuery {
	d.query = d.query.Asc("ID")
	return d
}

func (d *AsyncTaskQuery) AscConfigKey() *AsyncTaskQuery {
	d.query = d.query.Asc("ConfigKey")
	return d
}

func (d *AsyncTaskQuery) AscStatus() *AsyncTaskQuery {
	d.query = d.query.Asc("Status")
	return d
}

func (d *AsyncTaskQuery) AscStartAt() *AsyncTaskQuery {
	d.query = d.query.Asc("StartAt")
	return d
}

func (d *AsyncTaskQuery) AscFinishAt() *AsyncTaskQuery {
	d.query = d.query.Asc("FinishAt")
	return d
}

func (d *AsyncTaskQuery) AscUpdatedAt() *AsyncTaskQuery {
	d.query = d.query.Asc("UpdatedAt")
	return d
}

func (d *AsyncTaskQuery) DescID() *AsyncTaskQuery {
	d.query = d.query.Desc("ID")
	return d
}

func (d *AsyncTaskQuery) DescConfigKey() *AsyncTaskQuery {
	d.query = d.query.Desc("ConfigKey")
	return d
}

func (d *AsyncTaskQuery) DescStatus() *AsyncTaskQuery {
	d.query = d.query.Desc("Status")
	return d
}

func (d *AsyncTaskQuery) DescStartAt() *AsyncTaskQuery {
	d.query = d.query.Desc("StartAt")
	return d
}

func (d *AsyncTaskQuery) DescFinishAt() *AsyncTaskQuery {
	d.query = d.query.Desc("FinishAt")
	return d
}

func (d *AsyncTaskQuery) DescUpdatedAt() *AsyncTaskQuery {
	d.query = d.query.Desc("UpdatedAt")
	return d
}

func (d *AsyncTaskQuery) Start(s string) *AsyncTaskQuery {
	d.query = d.query.Start(s)
	return d
}

func (d *AsyncTaskQuery) End(s string) *AsyncTaskQuery {
	d.query = d.query.End(s)
	return d
}

func (d *AsyncTaskQuery) Limit(n int) *AsyncTaskQuery {
	d.query = d.query.Limit(n)
	return d
}

func (d *AsyncTaskQuery) ViaKeys() *AsyncTaskQuery {
	d.viaKeys = true
	return d
}

func (d *AsyncTaskQuery) GetAll(ctx context.Context) ([]*datastore.Key, []AsyncTask, error) {
	if d.viaKeys {
		keys, err := d.query.KeysOnly().GetAll(ctx, nil)
		if err != nil {
			return nil, nil, err
		}
		_, ents, err := async_taskKindInstance.GetMulti(ctx, keys)
		if err != nil {
			return nil, nil, err
		}
		list := make([]AsyncTask, len(ents))
		for i, e := range ents {
			list[i] = *e
		}
		return keys, list, nil
	}
	var ent []AsyncTask
	keys, err := d.query.GetAll(ctx, &ent)
	if err != nil {
		return nil, nil, err
	}
	return keys, ent, nil
}

func (d *AsyncTaskQuery) MustGetAll(ctx context.Context) ([]*datastore.Key, []AsyncTask) {
	keys, ents, err := d.GetAll(ctx)
	xerrors.MustNil(err)
	return keys, ents
}

func (d *AsyncTaskQuery) Count(ctx context.Context) (int, error) {
	return d.query.Count(ctx)
}

func (d *AsyncTaskQuery) MustCount(ctx context.Context) int {
	c, err := d.query.Count(ctx)
	xerrors.MustNil(err)
	return c
}

func (d *AsyncTaskQuery) Run(ctx context.Context) (*AsyncTaskIterator, error) {
	iter, err := d.query.Run(ctx)
	if err != nil {
		return nil, err
	}
	return &AsyncTaskIterator{
		ctx:     ctx,
		iter:    iter,
		viaKeys: d.viaKeys,
	}, err
}

func (d *AsyncTaskQuery) MustRun(ctx context.Context) *AsyncTaskIterator {
	iter, err := d.Run(ctx)
	xerrors.MustNil(err)
	return iter
}

func (d *AsyncTaskQuery) RunAll(ctx context.Context) ([]datastore.Key, []AsyncTask, string, error) {
	iter, err := d.Run(ctx)
	if err != nil {
		return nil, nil, "", err
	}
	var keys []datastore.Key
	var ents []AsyncTask
	for {
		key, ent, err := iter.Next()
		if err != nil {
			return nil, nil, "", err
		}
		if ent == nil {
			cursor, err := iter.iter.Cursor()
			if err != nil {
				return nil, nil, "", err
			}
			return keys, ents, cursor.String(), nil
		}
		keys = append(keys, *key)
		ents = append(ents, *ent)
	}
}

func (d *AsyncTaskQuery) MustRunAll(ctx context.Context) ([]datastore.Key, []AsyncTask, string) {
	keys, ents, next, err := d.RunAll(ctx)
	xerrors.MustNil(err)
	return keys, ents, next
}

type AsyncTaskIterator struct {
	ctx     context.Context
	iter    *datastore.Iterator
	viaKeys bool
}

func (iter *AsyncTaskIterator) Cursor() (datastore.Cursor, error) {
	return iter.iter.Cursor()
}

func (iter *AsyncTaskIterator) MustCursor() datastore.Cursor {
	c, err := iter.iter.Cursor()
	xerrors.MustNil(err)
	return c
}

func (iter *AsyncTaskIterator) Next() (*datastore.Key, *AsyncTask, error) {
	if iter.viaKeys {
		key, err := iter.iter.Next(nil)
		if err != nil {
			if err == datastore.Done {
				return nil, nil, nil
			}
			return nil, nil, err
		}
		_, ent, err := async_taskKindInstance.Get(iter.ctx, key)
		if err != nil {
			return nil, nil, err
		}
		return key, ent, nil

	}
	var ent AsyncTask
	key, err := iter.iter.Next(&ent)
	if err != nil {
		if err == datastore.Done {
			return nil, nil, nil
		}
		return nil, nil, err
	}
	return key, &ent, nil
}

func (iter *AsyncTaskIterator) MustNext() (*datastore.Key, *AsyncTask) {
	key, ent, err := iter.Next()
	xerrors.MustNil(err)
	return key, ent
}

var AAsyncTaskKindInstance = &AsyncTaskKind{}
