// Code generated by github.com/yssk22/go/generator DO NOT EDIT.
// eslint-edisable

export type Progress = {
    total: number,
    current: number,
    message?: string,
};
export type TaskStatus = {
    id: string,
    status: Status,
    start_at?: ?Date,
    finish_at?: ?Date,
    error?: ?string,
    progress?: ?Progress,
};
